"""Add 40 lecture questions (d282l_161..200) and 100 combined questions (d282_101..200) for DA-282 Horticulture."""
import sys, random, os
sys.stdout.reconfigure(encoding='utf-8')

BASE = r"C:\Users\bioas\Agricet Mock Test Series\src\data\questions"

def shuffle_q(questions):
    for q in questions:
        opts = q['options'][:]
        ct = opts[q['correct']]
        seed = abs(hash(repr(opts))) % (2**31)
        rng = random.Random(seed)
        rng.shuffle(opts)
        q['options'] = opts
        q['correct'] = opts.index(ct)
    return questions

def append_to_file(fpath, questions, is_lecture):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    content = content.rstrip()
    if content.endswith('];'):
        content = content[:-2].rstrip()
    parts = []
    for q in questions:
        opts_str = ', '.join('"' + o.replace('\\', '\\\\').replace('"', '\\"') + '"' for o in q['options'])
        qt = q['question'].replace('\\', '\\\\').replace('"', '\\"')
        et = q['explanation'].replace('\\', '\\\\').replace('"', '\\"')
        if is_lecture:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject'] + '", lecture: "' + q['lecture']
                 + '", lectureNo: ' + str(q['lectureNo']) + ',\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        else:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject']
                 + '",\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        parts.append(s)
    new_content = content + ',\n' + ',\n'.join(parts) + '\n\n];'
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"  Appended {len(questions)} questions to {os.path.basename(fpath)}")

# ── 40 new lecture questions (d282l_161 to d282l_200) ─────────────────────────
LQ = [
  {'id':'d282l_161','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'The word horticulture is derived from Latin words meaning:',
   'options':['Study of plants','Garden cultivation (hortus=garden + colere=cultivation)','Science of farming','Plant biology'],
   'correct':1,'explanation':'Horticulture comes from Latin hortus (garden) + colere (to cultivate). It is the science and art of garden crop production.',
   'difficulty':'medium'},
  {'id':'d282l_162','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'Pomology is the branch of horticulture dealing with:',
   'options':['Vegetable cultivation','Fruit crop cultivation and study','Flower cultivation','Spice production'],
   'correct':1,'explanation':'Pomology is the branch of horticulture concerned with the science and practice of growing fruit crops.',
   'difficulty':'easy'},
  {'id':'d282l_163','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'Olericulture is the branch of horticulture dealing with:',
   'options':['Fruit crops','Vegetable crops','Flower crops','Plantation crops'],
   'correct':1,'explanation':'Olericulture is the branch of horticulture dealing with the production, storage, and marketing of vegetables.',
   'difficulty':'easy'},
  {'id':'d282l_164','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'Floriculture is the branch of horticulture concerned with:',
   'options':['Fruit production','Vegetable production','Flower and ornamental plant production','Spice production'],
   'correct':2,'explanation':'Floriculture deals with the cultivation of flowers and ornamental plants for decorative purposes, bouquets, and gardens.',
   'difficulty':'easy'},
  {'id':'d282l_165','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'ASSERTION-REASON: Assertion (A): Mango is called the King of Fruits in India. Reason (R): Mango is the national fruit of India, widely cultivated, and consumed across the country with high economic importance.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Mango (Mangifera indica) is the national fruit of India and called the King of Fruits due to its wide cultivation, variety, and economic importance. R explains A.',
   'difficulty':'easy'},
  {'id':'d282l_166','subject':'da-282','lecture':'lecture-11','lectureNo':11,
   'question':'Match horticulture branches (Col A) with focus crops (Col B) and examples (Col C): Col A: 1-Pomology, 2-Olericulture, 3-Floriculture, 4-Spices. Col B: P-condiments, Q-fruits, R-flowers, S-vegetables. Col C: i-rose, ii-mango, iii-tomato, iv-cardamom',
   'options':['1-Q-ii, 2-S-iii, 3-R-i, 4-P-iv','1-P-iv, 2-Q-ii, 3-S-iii, 4-R-i','1-R-i, 2-P-iv, 3-Q-ii, 4-S-iii','1-S-iii, 2-R-i, 3-P-iv, 4-Q-ii'],
   'correct':0,'explanation':'Pomology (fruits=mango=ii), Olericulture (vegetables=tomato=iii), Floriculture (flowers=rose=i), Spices (condiments=cardamom=iv).',
   'difficulty':'hard'},
  {'id':'d282l_167','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'The botanical name of mango is:',
   'options':['Musa paradisiaca','Mangifera indica','Citrus sinensis','Psidium guajava'],
   'correct':1,'explanation':'Mango (Mangifera indica) belongs to the family Anacardiaceae. It is the national fruit of India.',
   'difficulty':'easy'},
  {'id':'d282l_168','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'The botanical name of banana is:',
   'options':['Mangifera indica','Musa paradisiaca','Vitis vinifera','Carica papaya'],
   'correct':1,'explanation':'Banana (Musa paradisiaca) belongs to the family Musaceae. It is one of the most widely consumed fruits globally.',
   'difficulty':'easy'},
  {'id':'d282l_169','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'Grapes belong to which botanical family?',
   'options':['Anacardiaceae','Musaceae','Vitaceae','Rutaceae'],
   'correct':2,'explanation':'Grapes (Vitis vinifera) belong to the family Vitaceae. Grapes are used for fresh consumption, wine, raisins, and juice.',
   'difficulty':'medium'},
  {'id':'d282l_170','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'Which fruit is known as the Queen of Fruits?',
   'options':['Mango','Banana','Mangosteen','Papaya'],
   'correct':2,'explanation':'Mangosteen (Garcinia mangostana) is called the Queen of Fruits due to its delicious taste and nutritional value.',
   'difficulty':'medium'},
  {'id':'d282l_171','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'Pomegranate (Punica granatum) is rich in which nutrient?',
   'options':['Vitamin C and antioxidants (punicalagins and anthocyanins)','Vitamin A','Calcium','Fat'],
   'correct':0,'explanation':'Pomegranate is rich in Vitamin C, antioxidants (punicalagins, punicic acid, anthocyanins), and is used for heart health and immunity.',
   'difficulty':'medium'},
  {'id':'d282l_172','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'ASSERTION-REASON: Assertion (A): Banana is a climacteric fruit. Reason (R): Climacteric fruits show a sharp rise in respiration (climacteric rise) and ethylene production during ripening, and can ripen after harvest.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Banana is climacteric — it ripens after harvest with a rise in ethylene. R correctly defines and explains climacteric behavior.',
   'difficulty':'medium'},
  {'id':'d282l_173','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'The botanical name of tomato is:',
   'options':['Solanum melongena','Solanum lycopersicum','Abelmoschus esculentus','Capsicum annuum'],
   'correct':1,'explanation':'Tomato (Solanum lycopersicum, formerly Lycopersicon esculentum) belongs to the family Solanaceae.',
   'difficulty':'easy'},
  {'id':'d282l_174','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'The botanical name of brinjal (eggplant) is:',
   'options':['Solanum lycopersicum','Solanum melongena','Abelmoschus esculentus','Cucumis sativus'],
   'correct':1,'explanation':'Brinjal/Eggplant (Solanum melongena) belongs to the family Solanaceae along with tomato, potato, and chilli.',
   'difficulty':'easy'},
  {'id':'d282l_175','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'Bhendi (Ladyfinger/Okra) belongs to which family?',
   'options':['Solanaceae','Cucurbitaceae','Malvaceae','Leguminosae'],
   'correct':2,'explanation':'Bhendi/Okra (Abelmoschus esculentus) belongs to the family Malvaceae (Hibiscus family). It is rich in fiber and vitamins.',
   'difficulty':'medium'},
  {'id':'d282l_176','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'ASSERTION-REASON: Assertion (A): Onion is a modified underground stem (bulb). Reason (R): Onion consists of fleshy scale leaves surrounding a central bud, all attached to a flattened stem (disc).',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Onion is a tunicated bulb — a modified stem with fleshy scale leaves on a compressed disc. R correctly explains the botanical structure.',
   'difficulty':'medium'},
  {'id':'d282l_177','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'Match vegetables (Col A) with families (Col B) and edible parts (Col C): Col A: 1-Tomato, 2-Onion, 3-Bhendi, 4-Cabbage. Col B: P-Brassicaceae, Q-Solanaceae, R-Malvaceae, S-Liliaceae. Col C: i-leaves, ii-bulb, iii-fruit, iv-capsule fruit',
   'options':['1-Q-iii, 2-S-ii, 3-R-iv, 4-P-i','1-P-i, 2-Q-iii, 3-S-ii, 4-R-iv','1-R-iv, 2-P-i, 3-Q-iii, 4-S-ii','1-S-ii, 2-R-iv, 3-P-i, 4-Q-iii'],
   'correct':0,'explanation':'Tomato (Solanaceae=fruit=iii), Onion (Liliaceae=bulb=ii), Bhendi (Malvaceae=capsule fruit=iv), Cabbage (Brassicaceae=leaves=i).',
   'difficulty':'hard'},
  {'id':'d282l_178','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'The botanical name of rose is:',
   'options':['Chrysanthemum morifolium','Rosa indica','Tagetes erecta','Jasminum sambac'],
   'correct':1,'explanation':'Rose (Rosa indica or Rosa hybrida) belongs to the family Rosaceae. It is the most important commercial flower crop.',
   'difficulty':'easy'},
  {'id':'d282l_179','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'Jasmine (Mogra) used in garlands in India belongs to which family?',
   'options':['Rosaceae','Asteraceae','Oleaceae','Malvaceae'],
   'correct':2,'explanation':'Jasmine (Jasminum sambac) belongs to the family Oleaceae (Olive family). It is India\'s most important cut flower and garland flower.',
   'difficulty':'medium'},
  {'id':'d282l_180','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'Marigold (Genda phool) is botanically known as:',
   'options':['Rosa indica','Chrysanthemum morifolium','Tagetes erecta','Jasminum sambac'],
   'correct':2,'explanation':'Marigold (Tagetes erecta) belongs to the family Asteraceae (Compositae). It is the most widely grown flower in India for festivals and garlands.',
   'difficulty':'easy'},
  {'id':'d282l_181','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'ASSERTION-REASON: Assertion (A): Post-harvest losses in horticultural crops are higher than in field crops. Reason (R): Horticultural produce (fruits, vegetables, flowers) are perishable, having high moisture content and being prone to mechanical damage and microbial spoilage.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Post-harvest losses in horticulture are 20-40%. R correctly explains the cause — perishable nature, high moisture, and susceptibility to spoilage.',
   'difficulty':'medium'},
  {'id':'d282l_182','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'Match flowers (Col A) with families (Col B) and uses (Col C): Col A: 1-Rose, 2-Jasmine, 3-Marigold, 4-Chrysanthemum. Col B: P-Asteraceae, Q-Rosaceae, R-Oleaceae, S-Asteraceae. Col C: i-temple/festival offerings, ii-garland and cut flower, iii-perfume and garland, iv-cut flower',
   'options':['1-Q-ii, 2-R-iii, 3-P-i, 4-S-iv','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-R-iii, 2-P-i, 3-S-iv, 4-Q-ii','1-S-iv, 2-P-i, 3-Q-ii, 4-R-iii'],
   'correct':0,'explanation':'Rose (Rosaceae=cut flower/garland=ii), Jasmine (Oleaceae=perfume/garland=iii), Marigold (Asteraceae=festival=i), Chrysanthemum (Asteraceae=cut flower=iv).',
   'difficulty':'hard'},
  {'id':'d282l_183','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Cardamom (Elettaria cardamomum) is called:',
   'options':['King of Spices','Queen of Spices','King of Fruits','Spice King'],
   'correct':1,'explanation':'Cardamom is called the Queen of Spices. It belongs to family Zingiberaceae and is the third most expensive spice in the world.',
   'difficulty':'medium'},
  {'id':'d282l_184','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Black pepper (Piper nigrum) is called:',
   'options':['King of Spices','Queen of Spices','Black Gold','Prince of Spices'],
   'correct':0,'explanation':'Black pepper (Piper nigrum) is called the King of Spices and also Black Gold. It is the most widely traded spice in the world.',
   'difficulty':'medium'},
  {'id':'d282l_185','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Coconut is botanically classified as a:',
   'options':['True fruit','Berry','Drupe (stone fruit)','Nut'],
   'correct':2,'explanation':'Coconut (Cocos nucifera) is botanically a drupe (stone fruit) with a fibrous outer husk (exocarp), a hard shell (endocarp), and edible flesh.',
   'difficulty':'hard'},
  {'id':'d282l_186','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'ASSERTION-REASON: Assertion (A): Chilli is a vegetable and also a spice. Reason (R): Green chilli is used as a vegetable while dry red chilli is used as a spice; both come from the same plant Capsicum annuum.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Chilli is dual-purpose — green fruit as vegetable, dry red fruit as spice. R correctly explains that both uses come from Capsicum annuum.',
   'difficulty':'medium'},
  {'id':'d282l_187','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Match spices (Col A) with botanical names (Col B) and families (Col C): Col A: 1-Cardamom, 2-Black pepper, 3-Turmeric, 4-Ginger. Col B: P-Zingiber officinale, Q-Curcuma longa, R-Piper nigrum, S-Elettaria cardamomum. Col C: i-Piperaceae, ii-Zingiberaceae, iii-Zingiberaceae, iv-Zingiberaceae',
   'options':['1-S-iv, 2-R-i, 3-Q-iii, 4-P-ii','1-R-i, 2-S-iv, 3-P-ii, 4-Q-iii','1-P-ii, 2-Q-iii, 3-R-i, 4-S-iv','1-Q-iii, 2-P-ii, 3-S-iv, 4-R-i'],
   'correct':0,'explanation':'Cardamom (Elettaria cardamomum=Zingiberaceae=iv), Black pepper (Piper nigrum=Piperaceae=i), Turmeric (Curcuma longa=Zingiberaceae=iii), Ginger (Zingiber officinale=Zingiberaceae=ii).',
   'difficulty':'hard'},
  {'id':'d282l_188','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'The edible part of cauliflower is the:',
   'options':['Root','Stem','Curd (compact flower head)','Leaf'],
   'correct':2,'explanation':'The edible part of cauliflower is the curd — a compact, immature flower head (inflorescence) of the plant Brassica oleracea var. botrytis.',
   'difficulty':'easy'},
  {'id':'d282l_189','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Which vegetable is known as the poor man\'s apple due to its high nutritional value and wide availability?',
   'options':['Onion','Tomato','Brinjal','Bitter gourd'],
   'correct':1,'explanation':'Tomato is called the poor man\'s apple due to its high content of Vitamin C, lycopene (antioxidant), and wide availability at affordable prices.',
   'difficulty':'medium'},
  {'id':'d282l_190','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Guava (Psidium guajava) is rich in:',
   'options':['Vitamin A','Vitamin C (highest among common fruits)','Calcium','Iron'],
   'correct':1,'explanation':'Guava has the highest Vitamin C content among common fruits — about 4-5 times more than oranges. It also contains Vitamin A, fiber, and potassium.',
   'difficulty':'medium'},
  {'id':'d282l_191','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'Citrus fruits belong to which botanical family?',
   'options':['Anacardiaceae','Rosaceae','Rutaceae','Vitaceae'],
   'correct':2,'explanation':'Citrus fruits (orange, lemon, lime, grapefruit) belong to the family Rutaceae. The genus Citrus includes most common citrus fruits.',
   'difficulty':'medium'},
  {'id':'d282l_192','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'Cucumber (Cucumis sativus) belongs to which family?',
   'options':['Solanaceae','Cucurbitaceae','Malvaceae','Brassicaceae'],
   'correct':1,'explanation':'Cucumber belongs to the family Cucurbitaceae (gourd family), along with bottle gourd, pumpkin, bitter gourd, and watermelon.',
   'difficulty':'medium'},
  {'id':'d282l_193','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'The edible part of potato is a:',
   'options':['Root','Fruit','Tuber (modified underground stem)','Bulb'],
   'correct':2,'explanation':'Potato (Solanum tuberosum) edible part is a tuber — a swollen underground stem with stored starch, bearing eyes (buds) for propagation.',
   'difficulty':'easy'},
  {'id':'d282l_194','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'Chrysanthemum is commercially important for:',
   'options':['Food production','Cut flowers, loose flowers for garlands, and potted plants','Timber','Spice production'],
   'correct':1,'explanation':'Chrysanthemum (Dendranthema grandiflora) is commercially important as a cut flower, loose flower for garlands, and potted ornamental plant.',
   'difficulty':'easy'},
  {'id':'d282l_195','subject':'da-282','lecture':'lecture-14','lectureNo':14,
   'question':'ASSERTION-REASON: Assertion (A): Drip irrigation is highly suitable for horticultural crops. Reason (R): Drip irrigation delivers water directly to the root zone, reducing water loss and improving water use efficiency for fruit and vegetable crops.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Drip irrigation is ideal for horticulture because it precisely delivers water to roots, reducing evaporation and weed growth. R correctly explains A.',
   'difficulty':'easy'},
  {'id':'d282l_196','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Turmeric (Curcuma longa) is propagated by:',
   'options':['Seeds','Rhizomes','Stem cuttings','Grafting'],
   'correct':1,'explanation':'Turmeric is propagated vegetatively through rhizomes (underground stems). Seeds are not commonly used for commercial production.',
   'difficulty':'medium'},
  {'id':'d282l_197','subject':'da-282','lecture':'lecture-15','lectureNo':15,
   'question':'Which of the following is a plantation crop?',
   'options':['Tomato','Paddy','Coconut','Marigold'],
   'correct':2,'explanation':'Plantation crops are perennial crops grown on large estates. Coconut (Cocos nucifera) is a plantation crop along with tea, coffee, rubber, and cashew.',
   'difficulty':'easy'},
  {'id':'d282l_198','subject':'da-282','lecture':'lecture-12','lectureNo':12,
   'question':'Match fruit types: Col A: 1-Mango, 2-Banana, 3-Grape, 4-Guava. Col B: P-Vitaceae, Q-Myrtaceae, R-Anacardiaceae, S-Musaceae. Col C: i-Mangifera indica, ii-Psidium guajava, iii-Vitis vinifera, iv-Musa paradisiaca',
   'options':['1-R-i, 2-S-iv, 3-P-iii, 4-Q-ii','1-P-iii, 2-Q-ii, 3-R-i, 4-S-iv','1-S-iv, 2-R-i, 3-Q-ii, 4-P-iii','1-Q-ii, 2-P-iii, 3-S-iv, 4-R-i'],
   'correct':0,'explanation':'Mango (Anacardiaceae=Mangifera indica=i), Banana (Musaceae=Musa paradisiaca=iv), Grape (Vitaceae=Vitis vinifera=iii), Guava (Myrtaceae=Psidium guajava=ii).',
   'difficulty':'hard'},
  {'id':'d282l_199','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'The edible part of carrot is a:',
   'options':['Bulb','Tuber','Taproot','Corm'],
   'correct':2,'explanation':'The edible part of carrot (Daucus carota) is a modified taproot that stores carbohydrates and beta-carotene (Vitamin A precursor).',
   'difficulty':'easy'},
  {'id':'d282l_200','subject':'da-282','lecture':'lecture-13','lectureNo':13,
   'question':'ASSERTION-REASON: Assertion (A): Bitter gourd is used medicinally to control blood sugar. Reason (R): Bitter gourd (Momordica charantia) contains insulin-like compounds (charantin, polypeptide-p) that help lower blood glucose levels.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Bitter gourd is widely used in Ayurveda for diabetes management. R correctly explains the biochemical basis — charantin and polypeptide-p.',
   'difficulty':'medium'},
]

# ── 100 combined questions (d282_101 to d282_200) ─────────────────────────────
CQ = [
  {'id':'d282_101','subject':'da-282','question':'Horticulture is derived from Latin words hortus and colere meaning:','options':['Study of plants','Garden cultivation','Science of farming','Plant biology'],'correct':1,'explanation':'Horticulture = hortus (garden) + colere (to cultivate). It is the science and art of garden crop production.','difficulty':'easy'},
  {'id':'d282_102','subject':'da-282','question':'Which branch of horticulture deals with fruit crop cultivation?','options':['Floriculture','Olericulture','Pomology','Spiciculture'],'correct':2,'explanation':'Pomology is the branch of horticulture dealing with the science and practice of growing fruit crops.','difficulty':'easy'},
  {'id':'d282_103','subject':'da-282','question':'Which branch of horticulture deals with vegetable cultivation?','options':['Pomology','Olericulture','Floriculture','Plantation crops'],'correct':1,'explanation':'Olericulture is the branch of horticulture dealing with the production, storage, and marketing of vegetables.','difficulty':'easy'},
  {'id':'d282_104','subject':'da-282','question':'The botanical name of mango is:','options':['Musa paradisiaca','Mangifera indica','Citrus sinensis','Psidium guajava'],'correct':1,'explanation':'Mango (Mangifera indica) belongs to family Anacardiaceae. It is the national fruit of India.','difficulty':'easy'},
  {'id':'d282_105','subject':'da-282','question':'The botanical name of banana is:','options':['Mangifera indica','Musa paradisiaca','Vitis vinifera','Carica papaya'],'correct':1,'explanation':'Banana (Musa paradisiaca) belongs to family Musaceae and is one of the world\'s most widely consumed fruits.','difficulty':'easy'},
  {'id':'d282_106','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Mango is called the King of Fruits. Reason (R): Mango is the national fruit of India with high economic importance and wide cultivation.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Mango is the King of Fruits and India\'s national fruit. R correctly explains its importance through cultivation, variety, and economic value.','difficulty':'easy'},
  {'id':'d282_107','subject':'da-282','question':'Match horticulture branches: Col A: 1-Pomology, 2-Olericulture, 3-Floriculture, 4-Spices. Col B: P-condiments, Q-fruits, R-flowers, S-vegetables. Col C: i-rose, ii-mango, iii-tomato, iv-cardamom','options':['1-Q-ii, 2-S-iii, 3-R-i, 4-P-iv','1-P-iv, 2-Q-ii, 3-S-iii, 4-R-i','1-R-i, 2-P-iv, 3-Q-ii, 4-S-iii','1-S-iii, 2-R-i, 3-P-iv, 4-Q-ii'],'correct':0,'explanation':'Pomology (fruits=mango=ii), Olericulture (vegetables=tomato=iii), Floriculture (flowers=rose=i), Spices (condiments=cardamom=iv).','difficulty':'hard'},
  {'id':'d282_108','subject':'da-282','question':'The botanical name of tomato is:','options':['Solanum melongena','Solanum lycopersicum','Abelmoschus esculentus','Capsicum annuum'],'correct':1,'explanation':'Tomato (Solanum lycopersicum) belongs to family Solanaceae. It is the most widely grown vegetable globally.','difficulty':'easy'},
  {'id':'d282_109','subject':'da-282','question':'Bhendi (Okra/Ladyfinger) belongs to which plant family?','options':['Solanaceae','Cucurbitaceae','Malvaceae','Leguminosae'],'correct':2,'explanation':'Bhendi/Okra (Abelmoschus esculentus) belongs to family Malvaceae (Hibiscus family). It is rich in fiber and vitamins.','difficulty':'medium'},
  {'id':'d282_110','subject':'da-282','question':'The botanical name of rose is:','options':['Chrysanthemum morifolium','Rosa indica','Tagetes erecta','Jasminum sambac'],'correct':1,'explanation':'Rose (Rosa indica/Rosa hybrida) belongs to family Rosaceae and is the most important commercial flower crop.','difficulty':'easy'},
  {'id':'d282_111','subject':'da-282','question':'Marigold is botanically known as:','options':['Rosa indica','Chrysanthemum morifolium','Tagetes erecta','Jasminum sambac'],'correct':2,'explanation':'Marigold (Tagetes erecta) belongs to family Asteraceae. It is the most widely grown flower in India for festivals and garlands.','difficulty':'easy'},
  {'id':'d282_112','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Post-harvest losses in horticultural crops are high (20-40%). Reason (R): Fruits, vegetables, and flowers are perishable with high moisture content, prone to mechanical damage and microbial spoilage.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Post-harvest losses in horticulture are 20-40%. R correctly explains the cause — perishable nature and susceptibility to spoilage.','difficulty':'medium'},
  {'id':'d282_113','subject':'da-282','question':'Black pepper (Piper nigrum) is called:','options':['King of Spices','Queen of Spices','Black Gold','Prince of Spices'],'correct':0,'explanation':'Black pepper is called the King of Spices and also Black Gold. It is the most widely traded spice in the world.','difficulty':'medium'},
  {'id':'d282_114','subject':'da-282','question':'Cardamom is called the:','options':['King of Spices','Queen of Spices','King of Fruits','Spice King'],'correct':1,'explanation':'Cardamom (Elettaria cardamomum) is called the Queen of Spices. It is the third most expensive spice in the world.','difficulty':'medium'},
  {'id':'d282_115','subject':'da-282','question':'Match vegetables: Col A: 1-Tomato, 2-Onion, 3-Bhendi, 4-Cabbage. Col B: P-Brassicaceae, Q-Solanaceae, R-Malvaceae, S-Liliaceae. Col C: i-leaves, ii-bulb, iii-fruit, iv-capsule fruit','options':['1-Q-iii, 2-S-ii, 3-R-iv, 4-P-i','1-P-i, 2-Q-iii, 3-S-ii, 4-R-iv','1-R-iv, 2-P-i, 3-Q-iii, 4-S-ii','1-S-ii, 2-R-iv, 3-P-i, 4-Q-iii'],'correct':0,'explanation':'Tomato (Solanaceae=fruit=iii), Onion (Liliaceae=bulb=ii), Bhendi (Malvaceae=capsule fruit=iv), Cabbage (Brassicaceae=leaves=i).','difficulty':'hard'},
  {'id':'d282_116','subject':'da-282','question':'The edible part of cauliflower is the:','options':['Root','Stem','Curd (compact flower head)','Leaf'],'correct':2,'explanation':'The edible part of cauliflower (Brassica oleracea var. botrytis) is the curd — a compact, immature flower head.','difficulty':'easy'},
  {'id':'d282_117','subject':'da-282','question':'Guava (Psidium guajava) is considered a nutritious fruit because it is high in:','options':['Vitamin A','Vitamin C (highest among common fruits)','Calcium','Fat'],'correct':1,'explanation':'Guava has the highest Vitamin C content among common fruits — about 4-5 times more than oranges.','difficulty':'medium'},
  {'id':'d282_118','subject':'da-282','question':'The botanical name of brinjal (eggplant) is:','options':['Solanum lycopersicum','Solanum melongena','Abelmoschus esculentus','Cucumis sativus'],'correct':1,'explanation':'Brinjal/Eggplant (Solanum melongena) belongs to family Solanaceae along with tomato, potato, and chilli.','difficulty':'easy'},
  {'id':'d282_119','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Onion is a modified underground stem. Reason (R): Onion consists of fleshy scale leaves surrounding a central bud, all attached to a flattened compressed disc (stem).','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Onion is a tunicated bulb — a modified stem with fleshy scale leaves on a compressed disc. R correctly explains this botanical structure.','difficulty':'medium'},
  {'id':'d282_120','subject':'da-282','question':'Match spices: Col A: 1-Cardamom, 2-Black pepper, 3-Turmeric, 4-Ginger. Col B: P-Zingiber officinale, Q-Curcuma longa, R-Piper nigrum, S-Elettaria cardamomum. Col C: i-Piperaceae, ii-Zingiberaceae family member, iii-Zingiberaceae, iv-Zingiberaceae','options':['1-S-iv, 2-R-i, 3-Q-iii, 4-P-ii','1-R-i, 2-S-iv, 3-P-ii, 4-Q-iii','1-P-ii, 2-Q-iii, 3-R-i, 4-S-iv','1-Q-iii, 2-P-ii, 3-S-iv, 4-R-i'],'correct':0,'explanation':'Cardamom (Elettaria=Zingiberaceae=iv), Black pepper (Piper=Piperaceae=i), Turmeric (Curcuma=Zingiberaceae=iii), Ginger (Zingiber=Zingiberaceae=ii).','difficulty':'hard'},
  {'id':'d282_121','subject':'da-282','question':'Floriculture deals with:','options':['Fruit production','Vegetable production','Flower and ornamental plant production','Spice production'],'correct':2,'explanation':'Floriculture deals with the cultivation of flowers and ornamental plants for decorative purposes, bouquets, and landscaping.','difficulty':'easy'},
  {'id':'d282_122','subject':'da-282','question':'Grapes (Vitis vinifera) belong to which family?','options':['Anacardiaceae','Musaceae','Vitaceae','Rutaceae'],'correct':2,'explanation':'Grapes (Vitis vinifera) belong to family Vitaceae. Grapes are used for fresh consumption, wine, raisins, and juice.','difficulty':'medium'},
  {'id':'d282_123','subject':'da-282','question':'Tomato is called the poor man\'s apple because:','options':['It is inexpensive and low in nutrition','It is high in Vitamin C, lycopene, and widely available at affordable prices','It resembles an apple in shape','It is grown only by poor farmers'],'correct':1,'explanation':'Tomato is called the poor man\'s apple due to high Vitamin C, lycopene (antioxidant), and wide availability at affordable prices.','difficulty':'medium'},
  {'id':'d282_124','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Banana is a climacteric fruit. Reason (R): Climacteric fruits show a rise in respiration rate and ethylene production during ripening, and can ripen after harvest.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Banana is climacteric — it ripens after harvest with a rise in ethylene. R correctly defines climacteric behavior.','difficulty':'medium'},
  {'id':'d282_125','subject':'da-282','question':'Coconut is botanically classified as a:','options':['True fruit','Berry','Drupe (stone fruit)','Nut'],'correct':2,'explanation':'Coconut (Cocos nucifera) is a drupe (stone fruit) with a fibrous outer husk (exocarp), hard shell (endocarp), and edible flesh (endosperm).','difficulty':'hard'},
  {'id':'d282_126','subject':'da-282','question':'Which is a plantation crop in horticulture?','options':['Tomato','Paddy','Coconut','Marigold'],'correct':2,'explanation':'Plantation crops are perennial crops grown on large estates. Coconut is a plantation crop along with tea, coffee, rubber, and cashew.','difficulty':'easy'},
  {'id':'d282_127','subject':'da-282','question':'Turmeric (Curcuma longa) is propagated commercially by:','options':['Seeds','Rhizomes','Stem cuttings','Grafting'],'correct':1,'explanation':'Turmeric is propagated vegetatively through rhizomes (underground stems). Seeds are not used for commercial production.','difficulty':'medium'},
  {'id':'d282_128','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Drip irrigation is highly suitable for horticultural crops. Reason (R): Drip irrigation delivers water directly to the root zone, reducing water loss and improving water use efficiency.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Drip irrigation is ideal for horticulture because it precisely delivers water to roots, reducing evaporation and weed growth. R correctly explains A.','difficulty':'easy'},
  {'id':'d282_129','subject':'da-282','question':'Jasmine (Mogra) used in garlands belongs to which family?','options':['Rosaceae','Asteraceae','Oleaceae','Malvaceae'],'correct':2,'explanation':'Jasmine (Jasminum sambac) belongs to family Oleaceae (Olive family). It is India\'s most important cut flower and garland flower.','difficulty':'medium'},
  {'id':'d282_130','subject':'da-282','question':'Match fruit types: Col A: 1-Mango, 2-Banana, 3-Grape, 4-Guava. Col B: P-Vitaceae, Q-Myrtaceae, R-Anacardiaceae, S-Musaceae. Col C: i-Mangifera indica, ii-Psidium guajava, iii-Vitis vinifera, iv-Musa paradisiaca','options':['1-R-i, 2-S-iv, 3-P-iii, 4-Q-ii','1-P-iii, 2-Q-ii, 3-R-i, 4-S-iv','1-S-iv, 2-R-i, 3-Q-ii, 4-P-iii','1-Q-ii, 2-P-iii, 3-S-iv, 4-R-i'],'correct':0,'explanation':'Mango (Anacardiaceae=Mangifera indica=i), Banana (Musaceae=Musa=iv), Grape (Vitaceae=Vitis vinifera=iii), Guava (Myrtaceae=Psidium=ii).','difficulty':'hard'},
  {'id':'d282_131','subject':'da-282','question':'The edible part of potato (Solanum tuberosum) is a:','options':['Root','Fruit','Tuber (modified underground stem)','Bulb'],'correct':2,'explanation':'Potato\'s edible part is a tuber — a swollen underground stem with stored starch and eyes (buds) for vegetative propagation.','difficulty':'easy'},
  {'id':'d282_132','subject':'da-282','question':'Citrus fruits belong to which botanical family?','options':['Anacardiaceae','Rosaceae','Rutaceae','Vitaceae'],'correct':2,'explanation':'Citrus fruits (orange, lemon, lime, grapefruit) belong to family Rutaceae. The genus Citrus includes most common citrus fruits.','difficulty':'medium'},
  {'id':'d282_133','subject':'da-282','question':'The edible part of carrot is a:','options':['Bulb','Tuber','Taproot','Corm'],'correct':2,'explanation':'The edible part of carrot (Daucus carota) is a modified taproot that stores carbohydrates and beta-carotene (Vitamin A precursor).','difficulty':'easy'},
  {'id':'d282_134','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Chilli is both a vegetable and a spice. Reason (R): Green chilli is used as a vegetable while dry red chilli is used as a spice; both come from Capsicum annuum.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Chilli is dual-purpose — green fruit as vegetable, dry red as spice. R correctly explains both uses come from Capsicum annuum.','difficulty':'medium'},
  {'id':'d282_135','subject':'da-282','question':'Cucumber (Cucumis sativus) belongs to family:','options':['Solanaceae','Cucurbitaceae','Malvaceae','Brassicaceae'],'correct':1,'explanation':'Cucumber belongs to family Cucurbitaceae (gourd family), along with bottle gourd, pumpkin, bitter gourd, and watermelon.','difficulty':'medium'},
  {'id':'d282_136','subject':'da-282','question':'Pomegranate (Punica granatum) is used medicinally because it is rich in:','options':['Vitamin D','Antioxidants including punicalagins and anthocyanins','Calcium only','Carbohydrates'],'correct':1,'explanation':'Pomegranate is rich in antioxidants (punicalagins, punicic acid, anthocyanins) and Vitamin C, used for heart health and immunity.','difficulty':'medium'},
  {'id':'d282_137','subject':'da-282','question':'Match flowers: Col A: 1-Rose, 2-Jasmine, 3-Marigold, 4-Chrysanthemum. Col B: P-Asteraceae, Q-Rosaceae, R-Oleaceae, S-Asteraceae. Col C: i-temple offerings, ii-garland and cut flower, iii-perfume and garland, iv-cut flower','options':['1-Q-ii, 2-R-iii, 3-P-i, 4-S-iv','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-R-iii, 2-P-i, 3-S-iv, 4-Q-ii','1-S-iv, 2-P-i, 3-Q-ii, 4-R-iii'],'correct':0,'explanation':'Rose (Rosaceae=garland/cut=ii), Jasmine (Oleaceae=perfume/garland=iii), Marigold (Asteraceae=temple=i), Chrysanthemum (Asteraceae=cut flower=iv).','difficulty':'hard'},
  {'id':'d282_138','subject':'da-282','question':'Which queen of spice is the third most expensive spice in the world?','options':['Black pepper','Turmeric','Cardamom','Ginger'],'correct':2,'explanation':'Cardamom (Elettaria cardamomum), called Queen of Spices, is the third most expensive spice after saffron and vanilla.','difficulty':'medium'},
  {'id':'d282_139','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Bitter gourd is used to control blood sugar. Reason (R): Bitter gourd (Momordica charantia) contains insulin-like compounds (charantin, polypeptide-p) that lower blood glucose.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Bitter gourd is used in Ayurveda for diabetes management. R correctly explains the biochemical basis — charantin and polypeptide-p.','difficulty':'medium'},
  {'id':'d282_140','subject':'da-282','question':'Which fruit is known as the Queen of Fruits?','options':['Mango','Banana','Mangosteen','Papaya'],'correct':2,'explanation':'Mangosteen (Garcinia mangostana) is called the Queen of Fruits due to its exquisite taste and nutritional value.','difficulty':'medium'},
  {'id':'d282_141','subject':'da-282','question':'The active antioxidant compound lycopene is found mainly in:','options':['Mango','Tomato (especially cooked/processed)','Banana','Cabbage'],'correct':1,'explanation':'Lycopene is a powerful antioxidant carotenoid found abundantly in tomatoes, especially in processed forms like tomato paste and ketchup.','difficulty':'medium'},
  {'id':'d282_142','subject':'da-282','question':'Ginger (Zingiber officinale) is propagated by:','options':['Seeds','Rhizomes','Stem cuttings','Layering'],'correct':1,'explanation':'Ginger is propagated vegetatively through rhizomes (underground stems). The rhizome pieces with nodes are planted for commercial cultivation.','difficulty':'easy'},
  {'id':'d282_143','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Tissue culture is used in horticulture for rapid propagation of plants. Reason (R): Tissue culture produces large numbers of disease-free, genetically uniform plants quickly from a small tissue sample.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Tissue culture (micropropagation) is widely used for banana, orchid, and potato propagation. R correctly explains the advantages.','difficulty':'medium'},
  {'id':'d282_144','subject':'da-282','question':'Which vegetable is botanically a fruit (has seeds inside)?','options':['Potato','Carrot','Tomato','Cabbage'],'correct':2,'explanation':'Botanically, tomato is a fruit because it develops from the flower\'s ovary and contains seeds. Culinary use treats it as a vegetable.','difficulty':'medium'},
  {'id':'d282_145','subject':'da-282','question':'The major coconut producing states in India include:','options':['Punjab, Haryana, UP','Kerala, Karnataka, Tamil Nadu, Andhra Pradesh','Bihar, West Bengal, Assam','Rajasthan, Gujarat, Maharashtra'],'correct':1,'explanation':'Kerala, Karnataka, Tamil Nadu, and Andhra Pradesh are the major coconut producing states, with Kerala being the largest producer.','difficulty':'easy'},
  {'id':'d282_146','subject':'da-282','question':'Match edible parts of vegetables: Col A: 1-Carrot, 2-Potato, 3-Onion, 4-Cauliflower. Col B: P-bulb, Q-curd, R-taproot, S-tuber. Col C: i-modified stem, ii-modified stem-leaves, iii-modified root, iv-flower head','options':['1-R-iii, 2-S-i, 3-P-ii, 4-Q-iv','1-P-ii, 2-Q-iv, 3-R-iii, 4-S-i','1-S-i, 2-P-ii, 3-Q-iv, 4-R-iii','1-Q-iv, 2-R-iii, 3-S-i, 4-P-ii'],'correct':0,'explanation':'Carrot (taproot=modified root=iii), Potato (tuber=modified stem=i), Onion (bulb=modified stem-leaves=ii), Cauliflower (curd=flower head=iv).','difficulty':'hard'},
  {'id':'d282_147','subject':'da-282','question':'Which is a non-climacteric fruit that does NOT ripen further after harvest?','options':['Mango','Banana','Papaya','Grape'],'correct':3,'explanation':'Grape is non-climacteric — it does not continue to ripen after harvest. Non-climacteric fruits must be harvested at full ripeness.','difficulty':'hard'},
  {'id':'d282_148','subject':'da-282','question':'The botanical name of papaya is:','options':['Mangifera indica','Carica papaya','Musa paradisiaca','Punica granatum'],'correct':1,'explanation':'Papaya (Carica papaya) belongs to family Caricaceae. It is a tropical fruit rich in Vitamin C, Vitamin A, and the enzyme papain.','difficulty':'easy'},
  {'id':'d282_149','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Rose is the most important commercial flower crop in India. Reason (R): Rose has the highest demand for cut flowers, loose flowers, rose water, and essential oil, making it commercially most valuable.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Rose is the leading commercial flower globally and in India. R correctly explains the diverse uses that make it commercially most valuable.','difficulty':'medium'},
  {'id':'d282_150','subject':'da-282','question':'Match plantation crops: Col A: 1-Coconut, 2-Coffee, 3-Tea, 4-Rubber. Col B: P-Euphorbiaceae, Q-Arecaceae, R-Rubiaceae, S-Theaceae. Col C: i-Hevea brasiliensis, ii-Cocos nucifera, iii-Coffea arabica, iv-Camellia sinensis','options':['1-Q-ii, 2-R-iii, 3-S-iv, 4-P-i','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-S-iv, 2-P-i, 3-Q-ii, 4-R-iii','1-R-iii, 2-S-iv, 3-P-i, 4-Q-ii'],'correct':0,'explanation':'Coconut (Arecaceae=Cocos nucifera=ii), Coffee (Rubiaceae=Coffea arabica=iii), Tea (Theaceae=Camellia sinensis=iv), Rubber (Euphorbiaceae=Hevea brasiliensis=i).','difficulty':'hard'},
  {'id':'d282_151','subject':'da-282','question':'The enzyme papain found in papaya is commercially used for:','options':['Making wine','Meat tenderizing and pharmaceutical industry','Paper production','Pesticide making'],'correct':1,'explanation':'Papain is a proteolytic (protein-digesting) enzyme from papaya used in meat tenderizers, pharmaceutical preparations, and textile industry.','difficulty':'medium'},
  {'id':'d282_152','subject':'da-282','question':'Which part of the onion plant is used as a spice?','options':['Stem','Bulb (modified underground stem)','Leaf','Root'],'correct':1,'explanation':'The bulb of onion is used as both a vegetable and spice. It is a tunicated bulb with fleshy scale leaves on a compressed stem disc.','difficulty':'easy'},
  {'id':'d282_153','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Cold storage is essential for extending shelf life of horticultural produce. Reason (R): Low temperatures slow down respiration, enzymatic activity, and microbial growth in perishable horticultural crops.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Cold storage extends shelf life. R correctly explains the mechanism — low temperatures slow respiration and microbial spoilage.','difficulty':'easy'},
  {'id':'d282_154','subject':'da-282','question':'Which compound in turmeric has anti-inflammatory and antioxidant properties?','options':['Piperine','Curcumin','Capsaicin','Allicin'],'correct':1,'explanation':'Curcumin is the main active compound in turmeric (Curcuma longa) responsible for its yellow color, anti-inflammatory, and antioxidant properties.','difficulty':'medium'},
  {'id':'d282_155','subject':'da-282','question':'Cashew nut (Anacardium occidentale) belongs to which family?','options':['Rutaceae','Myrtaceae','Anacardiaceae','Vitaceae'],'correct':2,'explanation':'Cashew (Anacardium occidentale) belongs to family Anacardiaceae, same family as mango. Goa, Kerala, and Andhra Pradesh are major producers.','difficulty':'medium'},
  {'id':'d282_156','subject':'da-282','question':'Which of the following is a cruciferous vegetable (family Brassicaceae)?','options':['Tomato','Bhendi','Cabbage','Brinjal'],'correct':2,'explanation':'Cabbage (Brassica oleracea var. capitata) belongs to family Brassicaceae (Cruciferae). Other cruciferous vegetables include cauliflower, broccoli, and radish.','difficulty':'easy'},
  {'id':'d282_157','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Grafting is commonly used for propagating mango. Reason (R): Grafting ensures that the new plant has the same desirable characteristics as the parent plant and comes to bearing earlier than seedlings.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Mango is propagated by grafting (veneer/inarching) for true-to-type plants that bear fruit earlier. R correctly explains the advantages of grafting.','difficulty':'medium'},
  {'id':'d282_158','subject':'da-282','question':'The water requirement of drip irrigation compared to flood irrigation is:','options':['More water (2x more)','Same amount of water','Less water (saves 30-50%)','Depends on crop only'],'correct':2,'explanation':'Drip irrigation saves 30-50% water compared to flood irrigation by delivering water directly to roots, reducing evaporation and runoff.','difficulty':'easy'},
  {'id':'d282_159','subject':'da-282','question':'Which state is the largest producer of mango in India?','options':['Tamil Nadu','Karnataka','Maharashtra','Uttar Pradesh'],'correct':3,'explanation':'Uttar Pradesh is the largest producer of mango in India, followed by Andhra Pradesh and Telangana. Dasheri and Langra are famous UP varieties.','difficulty':'medium'},
  {'id':'d282_160','subject':'da-282','question':'Match: Col A: 1-Mango variety, 2-Banana variety, 3-Grape variety, 4-Citrus type. Col B: P-Robusta, Q-Bangalore Blue, R-Alphonso, S-Nagpur Orange. Col C: i-Maharashtra specialty, ii-Robusta tissue culture variety, iii-Hapus/prized mango, iv-wine grape from Karnataka','options':['1-R-iii, 2-P-ii, 3-Q-iv, 4-S-i','1-P-ii, 2-Q-iv, 3-R-iii, 4-S-i','1-S-i, 2-R-iii, 3-P-ii, 4-Q-iv','1-Q-iv, 2-S-i, 3-P-ii, 4-R-iii'],'correct':0,'explanation':'Mango (Alphonso/Hapus=prized=iii), Banana (Robusta=tissue culture variety=ii), Grape (Bangalore Blue=wine grape Karnataka=iv), Citrus (Nagpur Orange=Maharashtra=i).','difficulty':'hard'},
  {'id':'d282_161','subject':'da-282','question':'The compound capsaicin that gives chilli its pungency belongs to which chemical class?','options':['Alkaloid','Terpene','Flavonoid','Carotenoid'],'correct':0,'explanation':'Capsaicin is a vanilloid alkaloid responsible for the pungent heat of chilli (Capsicum). It binds to pain receptors (TRPV1) in the mouth.','difficulty':'hard'},
  {'id':'d282_162','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Vegetables are broadly classified based on edible parts. Reason (R): Different parts of vegetables (roots, stems, leaves, flowers, fruits, seeds) are consumed, and crops are classified accordingly.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Vegetables are classified by edible part — root vegetables (carrot), stem (potato), leaf (cabbage), flower (cauliflower), fruit (tomato), seed (pea). R explains A.','difficulty':'easy'},
  {'id':'d282_163','subject':'da-282','question':'Onion cultivation in India is most prominent in which state?','options':['Punjab','Maharashtra','Uttar Pradesh','Rajasthan'],'correct':1,'explanation':'Maharashtra (especially Nashik) is the largest onion producing state in India, contributing about 35% of national production.','difficulty':'medium'},
  {'id':'d282_164','subject':'da-282','question':'Which nutrient is highest in green leafy vegetables?','options':['Vitamin C only','Iron, calcium, and Vitamin A (carotenoids)','Fat','Carbohydrates'],'correct':1,'explanation':'Green leafy vegetables (spinach, fenugreek, amaranth) are excellent sources of iron, calcium, Vitamin A (as carotenoids), and folate.','difficulty':'medium'},
  {'id':'d282_165','subject':'da-282','question':'Match: Col A: 1-Pomology, 2-Olericulture, 3-Floriculture, 4-Plantation crops. Examples: 1-Alphonso mango, 2-Nashik tomato, 3-Pune rose, 4-Munnar tea. Which correctly matches?','options':['1-Alphonso mango, 2-Nashik tomato, 3-Pune rose, 4-Munnar tea','1-Nashik tomato, 2-Alphonso mango, 3-Munnar tea, 4-Pune rose','1-Pune rose, 2-Munnar tea, 3-Alphonso mango, 4-Nashik tomato','1-Munnar tea, 2-Pune rose, 3-Nashik tomato, 4-Alphonso mango'],'correct':0,'explanation':'Pomology=fruit crops (Alphonso mango), Olericulture=vegetable crops (Nashik tomato), Floriculture=flower crops (Pune rose), Plantation=tea (Munnar tea).','difficulty':'medium'},
  {'id':'d282_166','subject':'da-282','question':'Chrysanthemum is commercially used for:','options':['Food production','Cut flowers, loose flowers, and potted plants','Timber production','Spice production'],'correct':1,'explanation':'Chrysanthemum (Dendranthema grandiflora) is commercially important as a cut flower, loose flower for garlands, and potted ornamental plant.','difficulty':'easy'},
  {'id':'d282_167','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Horticulture contributes significantly to India\'s export earnings. Reason (R): Horticultural products like grapes, mangoes, flowers, and spices are major export commodities from India.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Horticulture is a major export sector. R correctly lists grapes, mangoes, flowers, and spices as key export commodities.','difficulty':'easy'},
  {'id':'d282_168','subject':'da-282','question':'Integrated Pest Management (IPM) in horticulture involves:','options':['Using only chemical pesticides','Using only biological control','Combining biological, cultural, and chemical methods to manage pests with minimal pesticide use','Eliminating all insects from the farm'],'correct':2,'explanation':'IPM combines biological (natural enemies), cultural (crop rotation), mechanical, and chemical (when needed) methods for sustainable pest management.','difficulty':'medium'},
  {'id':'d282_169','subject':'da-282','question':'The fruit of pomegranate is botanically called a:','options':['Berry','Drupe','Balausta','Hesperidium'],'correct':2,'explanation':'Pomegranate fruit is botanically a balausta — a many-seeded berry with a tough leathery outer wall derived from fused sepals.','difficulty':'hard'},
  {'id':'d282_170','subject':'da-282','question':'Match: Col A: 1-Vegetative propagation method, 2-Sexual propagation. What is correct? Col A: 1-Cutting, 2-Layering, 3-Grafting, 4-Seeds. Purpose: 1-new plant from stem, 2-root before detach, 3-join two plants, 4-genetic variation','options':['1-Cutting=new plant from stem, 2-Layering=root before detach, 3-Grafting=join two plants, 4-Seeds=genetic variation','1-Seeds=new plant from stem, 2-Grafting=root before detach, 3-Layering=join two plants, 4-Cutting=genetic variation','1-Layering=join two plants, 2-Cutting=new plant from stem, 3-Seeds=root before detach, 4-Grafting=genetic variation','1-Grafting=genetic variation, 2-Seeds=join two plants, 3-Cutting=root before detach, 4-Layering=new plant from stem'],'correct':0,'explanation':'Cutting (new plant from stem portion), Layering (induce rooting before separation), Grafting (join scion and rootstock), Seeds (sexual, genetic variation).','difficulty':'medium'},
  {'id':'d282_171','subject':'da-282','question':'India is the _____ largest producer of fruits and vegetables in the world:','options':['1st','2nd','5th','10th'],'correct':1,'explanation':'India is the second largest producer of fruits and vegetables in the world after China, contributing significantly to global horticulture production.','difficulty':'medium'},
  {'id':'d282_172','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Protected cultivation (greenhouse/polyhouse) is used in horticulture. Reason (R): Protected cultivation provides controlled temperature, humidity, and light, enabling year-round production of high-value crops.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Greenhouses/polyhouses control growing conditions for high-value vegetables and flowers. R correctly explains the advantages of protected cultivation.','difficulty':'medium'},
  {'id':'d282_173','subject':'da-282','question':'Which spice is obtained from the dried stigmas of Crocus sativus flowers?','options':['Turmeric','Saffron','Cardamom','Black pepper'],'correct':1,'explanation':'Saffron (Kesar) is obtained from the dried stigmas of Crocus sativus. It is the world\'s most expensive spice by weight.','difficulty':'medium'},
  {'id':'d282_174','subject':'da-282','question':'The Queen of spices cardamom is mainly grown in:','options':['Punjab and Haryana','Rajasthan and Gujarat','Kerala and Karnataka (Cardamom Hills)','Maharashtra and Goa'],'correct':2,'explanation':'Cardamom is primarily grown in Kerala and Karnataka (in the Cardamom Hills / Idukki district of Kerala), which produce most of India\'s cardamom.','difficulty':'medium'},
  {'id':'d282_175','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Onion causes tears when cut. Reason (R): Cutting onion releases volatile sulphur compounds (syn-propanethial-S-oxide) that irritate the eyes and trigger tear production.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Cutting onion releases volatile sulphur compounds that irritate lacrimal glands, causing tears. R correctly explains the biochemical mechanism.','difficulty':'medium'},
  {'id':'d282_176','subject':'da-282','question':'Sprinkler irrigation in horticulture is especially suitable for:','options':['Heavy clay soils with flat terrain','Sandy soils and undulating terrain with vegetables and flowers','Only rice cultivation','Flooded paddy fields'],'correct':1,'explanation':'Sprinkler irrigation suits sandy soils, undulating terrain, and crops like vegetables and flowers where uniform water distribution is needed.','difficulty':'medium'},
  {'id':'d282_177','subject':'da-282','question':'The edible part of peas (Pisum sativum) are the:','options':['Roots','Seeds (inside the pod)','Stem','Leaves'],'correct':1,'explanation':'The edible part of peas is the seeds (green peas) inside the pod. The immature pod itself is also consumed as a vegetable.','difficulty':'easy'},
  {'id':'d282_178','subject':'da-282','question':'Match: Col A: 1-Alphonso, 2-Raspuri, 3-Dashehari, 4-Kesar. All are varieties of _____ crop.','options':['Banana varieties','Mango varieties','Grape varieties','Citrus varieties'],'correct':1,'explanation':'Alphonso (Maharashtra), Raspuri (Karnataka), Dashehari (UP), and Kesar (Gujarat) are all popular mango (Mangifera indica) varieties.','difficulty':'medium'},
  {'id':'d282_179','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Fruit ripening can be artificially induced by ethylene gas. Reason (R): Ethylene is a plant hormone that triggers the biochemical changes associated with fruit ripening, including softening and colour change.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Ethylene gas is used commercially to ripen bananas and mangoes. R correctly explains ethylene\'s role as a ripening hormone.','difficulty':'medium'},
  {'id':'d282_180','subject':'da-282','question':'Which of the following is an aromatic plant crop cultivated in horticulture?','options':['Teak','Lemongrass (Cymbopogon citratus)','Bamboo','Paddy'],'correct':1,'explanation':'Lemongrass (Cymbopogon citratus) is an aromatic plant cultivated for its essential oil used in cosmetics, food flavoring, and aromatherapy.','difficulty':'medium'},
  {'id':'d282_181','subject':'da-282','question':'Bed formation in vegetable cultivation helps in:','options':['Reducing plant density','Improving drainage, aeration, and ease of cultivation operations','Increasing weed growth','Reducing fertilizer use'],'correct':1,'explanation':'Raised beds improve drainage, soil aeration, ease weeding and irrigation operations, and facilitate better root development in vegetable crops.','difficulty':'easy'},
  {'id':'d282_182','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Organic farming is gaining importance in horticulture. Reason (R): Organic horticultural products command premium prices in domestic and international markets, and consumers prefer chemical-free produce.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Organic horticulture is growing due to premium prices and consumer health consciousness. R correctly explains the market and consumer drivers.','difficulty':'easy'},
  {'id':'d282_183','subject':'da-282','question':'The botanical name of coconut is:','options':['Mangifera indica','Cocos nucifera','Artocarpus integrifolia','Carica papaya'],'correct':1,'explanation':'Coconut (Cocos nucifera) belongs to family Arecaceae (palm family). It is called Kalpavriksha due to its multiple uses.','difficulty':'easy'},
  {'id':'d282_184','subject':'da-282','question':'Which state is India\'s largest grape producer?','options':['Punjab','Maharashtra','Tamil Nadu','Andhra Pradesh'],'correct':1,'explanation':'Maharashtra (Nashik district) is India\'s largest grape producing state, accounting for over 80% of total production. Nashik is known as the Wine Capital of India.','difficulty':'medium'},
  {'id':'d282_185','subject':'da-282','question':'Match propagation methods: Col A: 1-Rose, 2-Mango, 3-Banana, 4-Grape. Method: P-Suckers/rhizomes, Q-Cuttings/budding, R-Grafting/budding, S-Cuttings/hardwood. Col C: i-stone grafting, ii-tongue grafting, iii-sword sucker, iv-stem cutting','options':['1-Q-iv, 2-R-i, 3-P-iii, 4-S-ii','1-R-i, 2-P-iii, 3-Q-iv, 4-S-ii','1-S-ii, 2-R-i, 3-Q-iv, 4-P-iii','1-P-iii, 2-Q-iv, 3-S-ii, 4-R-i'],'correct':0,'explanation':'Rose (cuttings=stem cutting=iv), Mango (veneer grafting=stone grafting=i), Banana (suckers/rhizomes=sword sucker=iii), Grape (hardwood cuttings=ii).','difficulty':'hard'},
  {'id':'d282_186','subject':'da-282','question':'Hydroponics in horticulture refers to:','options':['Growing crops in very humid conditions','Growing plants in nutrient-enriched water without soil','Growing crops under water','Growing crops in very alkaline soil'],'correct':1,'explanation':'Hydroponics is a method of growing plants in a nutrient solution (water + dissolved minerals) without soil, used for high-value vegetables and herbs.','difficulty':'medium'},
  {'id':'d282_187','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Brinjal (eggplant) is an indigenous crop of India. Reason (R): India is the primary centre of origin for brinjal (Solanum melongena), which has been cultivated here for thousands of years.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Brinjal originated in India and Southeast Asia. R correctly states India as the primary centre of origin, explaining why there is high diversity here.','difficulty':'medium'},
  {'id':'d282_188','subject':'da-282','question':'What is the role of mulching in horticulture?','options':['Increases soil temperature only','Conserves soil moisture, controls weeds, and maintains soil temperature','Provides nutrients directly to plants','Replaces fertilizer completely'],'correct':1,'explanation':'Mulching with straw, plastic, or organic material conserves moisture, suppresses weeds, regulates soil temperature, and reduces soil erosion.','difficulty':'easy'},
  {'id':'d282_189','subject':'da-282','question':'The Kiwi fruit (Actinidia deliciosa) is grown successfully in India in:','options':['Plains of Punjab','Himachal Pradesh and Uttarakhand hills','Rajasthan desert','Coastal Tamil Nadu'],'correct':1,'explanation':'Kiwi fruit requires cool temperate conditions and is commercially grown in Himachal Pradesh, Uttarakhand, and Arunachal Pradesh in India.','difficulty':'medium'},
  {'id':'d282_190','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): India has diverse agro-climatic zones suitable for growing a wide variety of horticultural crops. Reason (R): India\'s varied climate, soil, and altitude support tropical, subtropical, and temperate fruit and vegetable cultivation.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'India\'s diverse agro-climatic zones allow growing tropical (mango, banana), subtropical (citrus), and temperate (apple, pear) crops. R explains A.','difficulty':'easy'},
  {'id':'d282_191','subject':'da-282','question':'Which vegetable is the primary source of lycopene (a cancer-preventing antioxidant)?','options':['Carrot','Spinach','Tomato','Brinjal'],'correct':2,'explanation':'Tomato is the richest common dietary source of lycopene, a carotenoid antioxidant associated with reduced risk of cancer and heart disease.','difficulty':'medium'},
  {'id':'d282_192','subject':'da-282','question':'Pineapple (Ananas comosus) belongs to which botanical family?','options':['Musaceae','Bromeliaceae','Arecaceae','Rutaceae'],'correct':1,'explanation':'Pineapple (Ananas comosus) belongs to family Bromeliaceae. It is a multiple fruit and is rich in the enzyme bromelain.','difficulty':'medium'},
  {'id':'d282_193','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): India is the world\'s largest producer of spices. Reason (R): India produces over 50 varieties of spices and is the largest exporter of spices globally, supplying about 23% of global spice exports.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'India produces over 50 spice varieties and dominates global spice trade. R correctly explains India\'s position as the world\'s leading spice producer and exporter.','difficulty':'medium'},
  {'id':'d282_194','subject':'da-282','question':'The botanical name of okra (bhendi) is:','options':['Solanum lycopersicum','Cucumis sativus','Abelmoschus esculentus','Phaseolus vulgaris'],'correct':2,'explanation':'Okra/Bhendi (Abelmoschus esculentus) belongs to family Malvaceae. It is rich in dietary fiber and vitamins B and C.','difficulty':'easy'},
  {'id':'d282_195','subject':'da-282','question':'Which of the following is a correct feature of tropical fruits?','options':['They require frost for quality development','They grow best in temperatures above 20°C with high humidity','They cannot be stored in cold storage','They are always seedless'],'correct':1,'explanation':'Tropical fruits (mango, banana, papaya) require warm temperatures (above 20°C), high humidity, and are chilling-sensitive (damaged by cold storage below 10°C).','difficulty':'medium'},
  {'id':'d282_196','subject':'da-282','question':'Match aromatic and medicinal plants: Col A: 1-Lemongrass, 2-Turmeric, 3-Ginger, 4-Aloe vera. Use: P-skin healing, Q-anti-inflammatory, R-digestive/spice, S-essential oil. Botanical: i-Zingiber officinale, ii-Curcuma longa, iii-Aloe barbadensis, iv-Cymbopogon citratus','options':['1-S-iv, 2-Q-ii, 3-R-i, 4-P-iii','1-P-iii, 2-R-i, 3-S-iv, 4-Q-ii','1-Q-ii, 2-P-iii, 3-R-i, 4-S-iv','1-R-i, 2-S-iv, 3-Q-ii, 4-P-iii'],'correct':0,'explanation':'Lemongrass (essential oil=Cymbopogon=iv), Turmeric (anti-inflammatory=Curcuma=ii), Ginger (digestive/spice=Zingiber=i), Aloe vera (skin healing=Aloe barbadensis=iii).','difficulty':'hard'},
  {'id':'d282_197','subject':'da-282','question':'The process of removing flowers or immature fruits to improve quality of remaining fruits is called:','options':['Pruning','Thinning','Grafting','Budding'],'correct':1,'explanation':'Thinning (fruit thinning) involves removing excess flowers or young fruits to reduce competition, improve fruit size, and enhance quality of remaining fruits.',  'difficulty':'medium'},
  {'id':'d282_198','subject':'da-282','question':'India\'s National Horticulture Board (NHB) was established to:','options':['Regulate timber trade','Promote integrated development of horticulture industry in India','Control pesticide use only','Set up cold storage only'],'correct':1,'explanation':'National Horticulture Board (NHB), established in 1984, promotes integrated development of horticulture industry including production, processing, and marketing.',  'difficulty':'medium'},
  {'id':'d282_199','subject':'da-282','question':'ASSERTION-REASON: Assertion (A): Mango is propagated vegetatively rather than by seeds for commercial cultivation. Reason (R): Seed-grown mango plants do not come true to type and take longer to bear fruit (10-15 years vs 3-4 years for grafted plants).','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Mango is propagated by grafting to maintain varietal characteristics and reduce juvenile period. R correctly explains both advantages over seedling propagation.','difficulty':'medium'},
  {'id':'d282_200','subject':'da-282','question':'Match: Col A: 1-Vegetable preservation method, 2-Fruit processing product. Examples: 1-Pickling, 2-Canning, 3-Drying, 4-Jam. Method: P-sugar preservation, Q-heat sterilization, R-salt/acid preservation, S-dehydration. C: i-mango pickle, ii-tomato ketchup can, iii-raisin from grape, iv-strawberry jam','options':['1-R-i, 2-Q-ii, 3-S-iii, 4-P-iv','1-P-iv, 2-R-i, 3-Q-ii, 4-S-iii','1-S-iii, 2-P-iv, 3-R-i, 4-Q-ii','1-Q-ii, 2-S-iii, 3-P-iv, 4-R-i'],'correct':0,'explanation':'Pickling (salt/acid=mango pickle=i), Canning (heat sterilization=tomato can=ii), Drying (dehydration=raisin=iii), Jam (sugar preservation=strawberry jam=iv).','difficulty':'hard'},
]

LQ = shuffle_q(LQ)
CQ = shuffle_q(CQ)

append_to_file(os.path.join(BASE, 'da-282-lectures.ts'), LQ, True)
append_to_file(os.path.join(BASE, 'da-282.ts'), CQ, False)
print("DA-282 done!")
