"""Add 44 lecture questions (d281l_157..200) and 100 combined questions (d281_101..200) for DA-281 Forestry."""
import sys, random, os
sys.stdout.reconfigure(encoding='utf-8')

BASE = r"C:\Users\bioas\Agricet Mock Test Series\src\data\questions"

def shuffle_q(questions):
    for q in questions:
        opts = q['options'][:]
        ct = opts[q['correct']]
        seed = abs(hash(repr(opts))) % (2**31)
        rng = random.Random(seed)
        rng.shuffle(opts)
        q['options'] = opts
        q['correct'] = opts.index(ct)
    return questions

def append_to_file(fpath, questions, is_lecture):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    content = content.rstrip()
    if content.endswith('];'):
        content = content[:-2].rstrip()
    parts = []
    for q in questions:
        opts_str = ', '.join('"' + o.replace('\\', '\\\\').replace('"', '\\"') + '"' for o in q['options'])
        qt = q['question'].replace('\\', '\\\\').replace('"', '\\"')
        et = q['explanation'].replace('\\', '\\\\').replace('"', '\\"')
        if is_lecture:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject'] + '", lecture: "' + q['lecture']
                 + '", lectureNo: ' + str(q['lectureNo']) + ',\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        else:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject']
                 + '",\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        parts.append(s)
    new_content = content + ',\n' + ',\n'.join(parts) + '\n\n];'
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"  Appended {len(questions)} questions to {os.path.basename(fpath)}")

# ── 44 new lecture questions (d281l_157 to d281l_200) ─────────────────────────
LQ = [
  {'id':'d281l_157','subject':'da-281','lecture':'lecture-10','lectureNo':10,
   'question':'The botanical name of teak is:',
   'options':['Azadirachta indica','Tectona grandis','Eucalyptus globulus','Acacia nilotica'],
   'correct':1,'explanation':'Teak (Tectona grandis) is a tropical hardwood known for its durability and high timber value. It is the national tree of India.',
   'difficulty':'medium'},
  {'id':'d281l_158','subject':'da-281','lecture':'lecture-10','lectureNo':10,
   'question':'The word forest is derived from the Latin word:',
   'options':['Forestis','Foresta','Foris meaning outside','Foresta silva'],
   'correct':2,'explanation':'The word forest comes from the Latin word foris meaning outside — referring to uncultivated land outside the village boundary.',
   'difficulty':'medium'},
  {'id':'d281l_159','subject':'da-281','lecture':'lecture-10','lectureNo':10,
   'question':'India\'s total forest cover as a percentage of its geographical area is approximately:',
   'options':['33%','23%','15%','40%'],
   'correct':1,'explanation':'India\'s forest and tree cover is approximately 23% of its total geographical area of 327.7 million hectares (75.26 lakh sq km).',
   'difficulty':'medium'},
  {'id':'d281l_160','subject':'da-281','lecture':'lecture-10','lectureNo':10,
   'question':'The per capita forest area in India compared to world average:',
   'options':['India 1.6 ha vs world 0.11 ha','India 0.11 ha vs world average 1.6 ha','India 2.0 ha vs world 1.0 ha','India 0.5 ha vs world 0.5 ha'],
   'correct':1,'explanation':'India has only 0.11 ha of forest per capita compared to the world average of 1.6 ha, showing India is far below the world average.',
   'difficulty':'medium'},
  {'id':'d281l_161','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'Telangana\'s forest cover as a percentage of its total geographical area is approximately:',
   'options':['15.11%','35.11%','25.11%','45.11%'],
   'correct':2,'explanation':'Telangana has a forest cover of about 25.11% (28,854 sq km) of its total geographical area.',
   'difficulty':'medium'},
  {'id':'d281l_162','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'Which district of Telangana has the highest forest area?',
   'options':['Adilabad','Warangal','Nizamabad','Khammam'],
   'correct':3,'explanation':'Khammam district has the highest forest area in Telangana at 7,945 sq km, making it the most forested district.',
   'difficulty':'medium'},
  {'id':'d281l_163','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'The branch of forestry that deals with the study of trees is called:',
   'options':['Silviculture','Dendrology','Forest mensuration','Agroforestry'],
   'correct':1,'explanation':'Dendrology is the scientific study of trees and woody plants — their identification, classification, and characteristics.',
   'difficulty':'medium'},
  {'id':'d281l_164','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'Silviculture in forestry refers to:',
   'options':['Study of forest soils','Art and science of controlling the establishment, growth, composition and quality of forests','Measurement of timber volumes','Study of forest animals'],
   'correct':1,'explanation':'Silviculture is the art and science of controlling the establishment, growth, composition, health, and quality of forests to meet diverse needs.',
   'difficulty':'medium'},
  {'id':'d281l_165','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'ASSERTION-REASON: Assertion (A): Forests play a crucial role in maintaining the water cycle. Reason (R): Trees absorb water from the soil and release it into the atmosphere through transpiration.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Forests maintain the water cycle through transpiration, reducing surface runoff, and promoting rainfall. R correctly explains A.',
   'difficulty':'medium'},
  {'id':'d281l_166','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'Match forest types (Col A) with characteristics (Col B) and examples (Col C): Col A: 1-Tropical wet evergreen, 2-Tropical dry deciduous, 3-Thorn forest, 4-Mangrove. Col B: P-coastal swampy, Q-rainfall below 75cm, R-rainfall over 200cm, S-rainfall 100-200cm. Col C: i-Sundarbans, ii-Rajasthan, iii-Western Ghats, iv-Central India',
   'options':['1-R-iii, 2-S-iv, 3-Q-ii, 4-P-i','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-S-iv, 2-R-iii, 3-P-i, 4-Q-ii','1-Q-ii, 2-P-i, 3-S-iv, 4-R-iii'],
   'correct':0,'explanation':'Tropical wet evergreen (rainfall >200cm=Western Ghats=iii), Dry deciduous (100-200cm=Central India=iv), Thorn (<75cm=Rajasthan=ii), Mangrove (coastal=Sundarbans=i).',
   'difficulty':'hard'},
  {'id':'d281l_167','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'The botanical name of neem is:',
   'options':['Tectona grandis','Azadirachta indica','Dalbergia latifolia','Shorea robusta'],
   'correct':1,'explanation':'Neem (Azadirachta indica) is a multipurpose tree known for medicinal, pesticidal, and timber uses. It is called the village pharmacy.',
   'difficulty':'easy'},
  {'id':'d281l_168','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Bamboo belongs to which plant family?',
   'options':['Leguminosae','Gramineae (Poaceae)','Euphorbiaceae','Rubiaceae'],
   'correct':1,'explanation':'Bamboo belongs to the grass family Gramineae (Poaceae). It is the fastest growing woody plant and an important forest product.',
   'difficulty':'medium'},
  {'id':'d281l_169','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Subabul (Leucaena leucocephala) is primarily used for:',
   'options':['Only timber production','Fuelwood, fodder, and nitrogen fixation (multipurpose tree)','Only ornamental purposes','Only paper pulp'],
   'correct':1,'explanation':'Subabul is a multipurpose tree used for fuelwood, fodder, green manure, nitrogen fixation, and paper pulp — a key social forestry species.',
   'difficulty':'medium'},
  {'id':'d281l_170','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Ashwagandha (Withania somnifera) is classified as a:',
   'options':['Timber tree','Medicinal plant','Agroforestry tree','Ornamental plant'],
   'correct':1,'explanation':'Ashwagandha is an important medicinal plant (adaptogen) used in Ayurveda for stress relief, strength enhancement, and immunity.',
   'difficulty':'easy'},
  {'id':'d281l_171','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Aloe vera is used medicinally primarily for:',
   'options':['Timber production','Burn healing, skin care, and digestive health','Soil nitrogen fixation','Windbreak protection'],
   'correct':1,'explanation':'Aloe vera (Aloe barbadensis) is a succulent medicinal plant widely used for treating burns, skin conditions, and digestive problems.',
   'difficulty':'easy'},
  {'id':'d281l_172','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'ASSERTION-REASON: Assertion (A): Neem is called the village pharmacy in India. Reason (R): Almost every part of neem (leaves, bark, seeds, oil) has medicinal, pesticidal, or agricultural uses.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Neem is called the village pharmacy because its leaves, bark, seeds, and oil are used for medicine, biopesticides, and agriculture. R explains A.',
   'difficulty':'easy'},
  {'id':'d281l_173','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'Agroforestry is defined as:',
   'options':['Cultivation of forest trees only','A land use system where trees are combined with crops or livestock on the same unit of land','Growing trees in monoculture','Cultivation of medicinal plants only'],
   'correct':1,'explanation':'Agroforestry is a land use management system that combines trees with crops and/or livestock on the same land unit, providing multiple benefits.',
   'difficulty':'easy'},
  {'id':'d281l_174','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'Agrisilviculture refers to:',
   'options':['Trees + livestock combination','Trees + crops combination','Trees + fish farming combination','Trees + beekeeping combination'],
   'correct':1,'explanation':'Agrisilviculture is an agroforestry system combining trees (silvi-) with agricultural crops on the same land.',
   'difficulty':'medium'},
  {'id':'d281l_175','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'Silvopastoral agroforestry system combines:',
   'options':['Trees + crops','Trees + fish farming','Trees + livestock/pasture','Trees + beekeeping'],
   'correct':2,'explanation':'Silvopastoral combines trees (silvi-) with pasture and livestock (pastoral), providing fodder, shade, and other tree products.',
   'difficulty':'medium'},
  {'id':'d281l_176','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'Match agroforestry systems: Col A: 1-Agrisilviculture, 2-Silvopastoral, 3-Agrosilvopastoral, 4-Aquaforestry. Col B: P-trees+fish, Q-trees+crops+livestock, R-trees+livestock, S-trees+crops. Col C: i-paddy+fish ponds, ii-teak+paddy, iii-teak+sheep+grass, iv-teak+paddy+cattle',
   'options':['1-S-ii, 2-R-iii, 3-Q-iv, 4-P-i','1-P-i, 2-Q-iv, 3-R-iii, 4-S-ii','1-R-iii, 2-S-ii, 3-P-i, 4-Q-iv','1-Q-iv, 2-P-i, 3-S-ii, 4-R-iii'],
   'correct':0,'explanation':'Agrisilviculture (trees+crops=teak+paddy=ii), Silvopastoral (trees+livestock=teak+sheep=iii), Agrosilvopastoral (trees+crops+livestock=iv), Aquaforestry (trees+fish=i).',
   'difficulty':'hard'},
  {'id':'d281l_177','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'The National Forest Policy of India recommends that _____ of total land area should be under forests:',
   'options':['20%','33%','50%','10%'],
   'correct':1,'explanation':'The National Forest Policy (1988) of India recommends that 33% of the total land area (including hills and mountains) should be under forest cover.',
   'difficulty':'medium'},
  {'id':'d281l_178','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Social forestry in India refers to:',
   'options':['Forestry activities only within reserved forests','Growing trees on community, government wastelands, and farm boundaries for the benefit of local communities','Forest conservation for wild animals only','Commercial timber plantation only'],
   'correct':1,'explanation':'Social forestry involves growing trees on village/community land, road sides, and farm boundaries to meet local needs for fuelwood, fodder, and timber.',
   'difficulty':'easy'},
  {'id':'d281l_179','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Non-Timber Forest Products (NTFPs) include:',
   'options':['Logs and planks only','Bamboo, honey, medicinal plants, gums, and resins (all non-wood products)','Heavy machinery materials','Chemical fertilizers'],
   'correct':1,'explanation':'NTFPs are all forest products other than timber — including bamboo, honey, lac, gums, resins, medicinal plants, and wild fruits.',
   'difficulty':'easy'},
  {'id':'d281l_180','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Tamarind (Tamarindus indica) is used for:',
   'options':['Timber and fuel only','Edible fruit, medicinal uses, and food industry (souring agent)','Fodder only','Paper pulp only'],
   'correct':1,'explanation':'Tamarind is used as a souring agent in cooking, in medicines, for jam/candy production, and its wood is used for fuel and tools.',
   'difficulty':'easy'},
  {'id':'d281l_181','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'ASSERTION-REASON: Assertion (A): Eucalyptus is a controversial tree for agroforestry in India. Reason (R): Eucalyptus is known to deplete groundwater and soil nutrients while providing fast growth and high biomass.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Eucalyptus is controversial because while it grows fast and yields biomass, it depletes groundwater and impoverishes soil. R explains the controversy.',
   'difficulty':'medium'},
  {'id':'d281l_182','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Senna (Cassia angustifolia) is an important medicinal plant used primarily as a:',
   'options':['Wound healer','Natural laxative','Fever reducer','Blood pressure regulator'],
   'correct':1,'explanation':'Senna leaves and pods contain sennosides which are powerful natural laxatives used in Ayurveda and modern medicine.',
   'difficulty':'medium'},
  {'id':'d281l_183','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Lemongrass (Cymbopogon citratus) is grown primarily for:',
   'options':['Timber','Essential oil used in cosmetics, food flavoring, and aromatherapy','Fuelwood','Fodder for cattle'],
   'correct':1,'explanation':'Lemongrass is cultivated for its aromatic essential oil, which is used in cosmetics, food flavoring, mosquito repellents, and aromatherapy.',
   'difficulty':'medium'},
  {'id':'d281l_184','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'Forest mensuration deals with:',
   'options':['Growing trees in forests','Measurement of timber volume, tree height, diameter, and forest area','Study of forest diseases','Planting trees in degraded areas'],
   'correct':1,'explanation':'Forest mensuration is the branch of forestry concerned with measuring timber volumes, tree dimensions, and forest area to assess forest resources.',
   'difficulty':'medium'},
  {'id':'d281l_185','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'The girth of a tree is measured at a height of _____ from the ground (Diameter at Breast Height):',
   'options':['0.5 m','1.37 m','2.0 m','3.0 m'],
   'correct':1,'explanation':'DBH (Diameter at Breast Height) is measured at 1.37 meters (4.5 feet) from the ground — the standard in forest mensuration.',
   'difficulty':'hard'},
  {'id':'d281l_186','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'Which is a fire resistant tree species?',
   'options':['Eucalyptus','Bamboo','Teak','Sal (Shorea robusta)'],
   'correct':3,'explanation':'Sal (Shorea robusta) is known for its fire resistance. Teak also has some resistance, but Sal is specifically noted for withstanding forest fires.',
   'difficulty':'hard'},
  {'id':'d281l_187','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'ASSERTION-REASON: Assertion (A): Forests help in prevention of soil erosion. Reason (R): Tree roots bind the soil particles together and the canopy reduces the impact of rainfall on the soil surface.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Forests prevent soil erosion through roots binding soil and canopy intercepting raindrops. R correctly explains the mechanism behind A.',
   'difficulty':'easy'},
  {'id':'d281l_188','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'Match medicinal plants: Col A: 1-Ashwagandha, 2-Aloe vera, 3-Senna, 4-Lemongrass. Col B: P-laxative, Q-skin healing, R-adaptogen, S-essential oil. Col C: i-Cymbopogon, ii-Cassia angustifolia, iii-Withania somnifera, iv-Aloe barbadensis',
   'options':['1-R-iii, 2-Q-iv, 3-P-ii, 4-S-i','1-P-ii, 2-R-iii, 3-Q-iv, 4-S-i','1-S-i, 2-P-ii, 3-R-iii, 4-Q-iv','1-Q-iv, 2-S-i, 3-P-ii, 4-R-iii'],
   'correct':0,'explanation':'Ashwagandha (adaptogen=Withania somnifera=iii), Aloe vera (skin healing=Aloe barbadensis=iv), Senna (laxative=Cassia=ii), Lemongrass (essential oil=Cymbopogon=i).',
   'difficulty':'hard'},
  {'id':'d281l_189','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'The main objective of Joint Forest Management (JFM) in India is:',
   'options':['Commercial timber exploitation','Involving local communities in forest protection and management for shared benefits','Complete protection without human use','Converting forests to agriculture'],
   'correct':1,'explanation':'JFM was introduced in 1990 to involve local communities (through Village Forest Committees) in forest protection and management, sharing the benefits.',
   'difficulty':'medium'},
  {'id':'d281l_190','subject':'da-281','lecture':'lecture-10','lectureNo':10,
   'question':'The State tree of Telangana is:',
   'options':['Neem','Teak','Jammi tree (Prosopis cineraria)','Banyan'],
   'correct':2,'explanation':'The Jammi tree (Prosopis cineraria), also called Shami tree, is the State tree of Telangana. It is associated with the Dussehra festival.',
   'difficulty':'medium'},
  {'id':'d281l_191','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'Forest cover of India includes:',
   'options':['Reserved forests only','Reserved, protected, and unclassed forests','Commercial plantations only','Agroforestry areas only'],
   'correct':1,'explanation':'India classifies forests into Reserved Forests (strictly protected), Protected Forests, and Unclassed Forests based on the Indian Forest Act 1927.',
   'difficulty':'medium'},
  {'id':'d281l_192','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Which tree is known as Green Gold due to its commercial importance?',
   'options':['Neem','Subabul (Leucaena leucocephala)','Teak','Bamboo'],
   'correct':3,'explanation':'Bamboo is called Green Gold because of its rapid growth, versatility, and commercial value in construction, crafts, pulp, and furniture.',
   'difficulty':'medium'},
  {'id':'d281l_193','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'The ideal tree for windbreaks and shelterbelts is:',
   'options':['Bamboo','Eucalyptus','Casuarina','Teak'],
   'correct':2,'explanation':'Casuarina (Casuarina equisetifolia) is widely used for coastal windbreaks and shelterbelts due to its fast growth and wind-tolerant nature.',
   'difficulty':'medium'},
  {'id':'d281l_194','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Lac is a forest product harvested from:',
   'options':['Leaves of teak trees','Secretions of lac insects on host trees','Sap of eucalyptus trees','Roots of Acacia species'],
   'correct':1,'explanation':'Lac is a resinous secretion produced by the lac insect (Kerria lacca) on host trees like ber, kusum, and palash. It is an important NTFP.',
   'difficulty':'medium'},
  {'id':'d281l_195','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'Which of the following is a correct statement about mangrove forests?',
   'options':['They grow in dry arid conditions','They grow in coastal saline tidal areas and protect coastlines from erosion','They are found only in Himalayan regions','They are deciduous and shed leaves in winter'],
   'correct':1,'explanation':'Mangroves grow in coastal intertidal zones with saline water. They protect coastlines from erosion, cyclones, and tsunamis (e.g., Sundarbans).',
   'difficulty':'medium'},
  {'id':'d281l_196','subject':'da-281','lecture':'lecture-11','lectureNo':11,
   'question':'ASSERTION-REASON: Assertion (A): Deforestation leads to increased carbon dioxide in the atmosphere. Reason (R): Trees absorb CO2 during photosynthesis; when trees are cut, this absorption capacity is lost and CO2 released.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Deforestation releases stored carbon and removes CO2-absorbing trees. R correctly explains the mechanism by which deforestation increases atmospheric CO2.',
   'difficulty':'medium'},
  {'id':'d281l_197','subject':'da-281','lecture':'lecture-12','lectureNo':12,
   'question':'Match timber trees: Col A: 1-Teak, 2-Sandalwood, 3-Rosewood, 4-Sal. Col B: P-Dalbergia latifolia, Q-Shorea robusta, R-Tectona grandis, S-Santalum album. Col C: i-furniture, ii-fire resistant, iii-perfume/incense, iv-Karnataka rosewood',
   'options':['1-R-i, 2-S-iii, 3-P-iv, 4-Q-ii','1-S-iii, 2-R-i, 3-Q-ii, 4-P-iv','1-P-iv, 2-Q-ii, 3-R-i, 4-S-iii','1-Q-ii, 2-P-iv, 3-S-iii, 4-R-i'],
   'correct':0,'explanation':'Teak (Tectona grandis=i-furniture), Sandalwood (Santalum album=iii-perfume), Rosewood (Dalbergia latifolia=iv-Karnataka), Sal (Shorea robusta=ii-fire resistant).',
   'difficulty':'hard'},
  {'id':'d281l_198','subject':'da-281','lecture':'lecture-13','lectureNo':13,
   'question':'The Chipko movement in India was a protest against:',
   'options':['Industrial pollution of forests','Commercial deforestation and felling of trees in Himalayas','Poaching of wildlife','Forest fires'],
   'correct':1,'explanation':'Chipko movement (1973, Uttarakhand) was a non-violent protest where villagers hugged trees to prevent commercial felling — a landmark environmental movement.',
   'difficulty':'easy'},
  {'id':'d281l_199','subject':'da-281','lecture':'lecture-14','lectureNo':14,
   'question':'Which international body monitors global forest resources and publishes the Global Forest Resources Assessment?',
   'options':['UNDP','FAO (Food and Agriculture Organization)','World Bank','UNEP'],
   'correct':1,'explanation':'FAO (Food and Agriculture Organization of the United Nations) publishes the Global Forest Resources Assessment periodically.',
   'difficulty':'medium'},
  {'id':'d281l_200','subject':'da-281','lecture':'lecture-15','lectureNo':15,
   'question':'Match: Col A: 1-Carbon sequestration, 2-Soil conservation, 3-Water table, 4-Biodiversity. Functions of forests. Col B: P-root systems bind soil, Q-stores carbon dioxide, R-habitat for plants and animals, S-tree roots recharge groundwater. Col C: i-climate change mitigation, ii-erosion prevention, iii-animal habitats, iv-well water level',
   'options':['1-Q-i, 2-P-ii, 3-S-iv, 4-R-iii','1-P-ii, 2-Q-i, 3-R-iii, 4-S-iv','1-S-iv, 2-R-iii, 3-P-ii, 4-Q-i','1-R-iii, 2-S-iv, 3-Q-i, 4-P-ii'],
   'correct':0,'explanation':'Carbon sequestration (stores CO2=climate mitigation=i), Soil conservation (roots bind soil=erosion prevention=ii), Water table (roots recharge=well level=iv), Biodiversity (habitat=animals=iii).',
   'difficulty':'hard'},
]

# ── 100 combined questions (d281_101 to d281_200) ─────────────────────────────
CQ = [
  {'id':'d281_101','subject':'da-281','question':'The word forest is derived from the Latin word foris meaning:','options':['Inside boundary','Outside (uncultivated land outside village)','Forest animals','Timber trees'],'correct':1,'explanation':'Forest comes from Latin foris meaning outside — referring to uncultivated land outside the village or cultivation boundary.','difficulty':'medium'},
  {'id':'d281_102','subject':'da-281','question':'India\'s forest and tree cover is approximately _____ of its total geographical area:','options':['33%','23%','15%','40%'],'correct':1,'explanation':'India\'s forest and tree cover is approximately 23% of its total geographical area of 327.7 million hectares.','difficulty':'medium'},
  {'id':'d281_103','subject':'da-281','question':'Per capita forest area in India is:','options':['1.6 ha','3.2 ha','0.11 ha','0.5 ha'],'correct':2,'explanation':'India has only 0.11 ha of forest per capita, far below the world average of 1.6 ha.','difficulty':'medium'},
  {'id':'d281_104','subject':'da-281','question':'Telangana\'s forest area is approximately:','options':['10,000 sq km','18,000 sq km','28,854 sq km','45,000 sq km'],'correct':2,'explanation':'Telangana has a forest cover of about 28,854 sq km, constituting approximately 25.11% of its total area.','difficulty':'medium'},
  {'id':'d281_105','subject':'da-281','question':'The district of Telangana with the highest forest area is:','options':['Adilabad','Warangal','Nizamabad','Khammam'],'correct':3,'explanation':'Khammam district has the highest forest area in Telangana at 7,945 sq km.','difficulty':'medium'},
  {'id':'d281_106','subject':'da-281','question':'The botanical name of teak is:','options':['Azadirachta indica','Tectona grandis','Eucalyptus globulus','Dalbergia latifolia'],'correct':1,'explanation':'Teak (Tectona grandis) is a tropical hardwood native to South and Southeast Asia, known for its durability.','difficulty':'medium'},
  {'id':'d281_107','subject':'da-281','question':'Silviculture is the branch of forestry concerned with:','options':['Tree identification','Timber measurement','Controlling forest establishment, growth, composition and quality','Forest animal study'],'correct':2,'explanation':'Silviculture is the art and science of controlling the establishment, growth, composition, and quality of forests.','difficulty':'medium'},
  {'id':'d281_108','subject':'da-281','question':'Dendrology is the scientific study of:','options':['Forest soils','Trees and woody plants','Timber volumes','Forest insects'],'correct':1,'explanation':'Dendrology is the scientific study of trees and woody plants — their identification, classification, and characteristics.','difficulty':'medium'},
  {'id':'d281_109','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Forests help maintain the water cycle. Reason (R): Trees absorb water from soil and release it through transpiration, contributing to rainfall.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Forests maintain the water cycle through transpiration, reducing runoff, and promoting rainfall. R correctly explains A.','difficulty':'medium'},
  {'id':'d281_110','subject':'da-281','question':'Match forest types: Col A: 1-Tropical wet evergreen, 2-Tropical dry deciduous, 3-Thorn forest, 4-Mangrove. Col B: P-coastal, Q-rainfall below 75cm, R-rainfall over 200cm, S-rainfall 100-200cm. Col C: i-Sundarbans, ii-Rajasthan, iii-Western Ghats, iv-Central India','options':['1-R-iii, 2-S-iv, 3-Q-ii, 4-P-i','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-S-iv, 2-R-iii, 3-P-i, 4-Q-ii','1-Q-ii, 2-P-i, 3-S-iv, 4-R-iii'],'correct':0,'explanation':'Tropical wet evergreen (>200cm=Western Ghats=iii), Dry deciduous (100-200cm=Central India=iv), Thorn (<75cm=Rajasthan=ii), Mangrove (coastal=Sundarbans=i).','difficulty':'hard'},
  {'id':'d281_111','subject':'da-281','question':'The botanical name of neem is:','options':['Tectona grandis','Azadirachta indica','Dalbergia latifolia','Shorea robusta'],'correct':1,'explanation':'Neem (Azadirachta indica) is a multipurpose tree known for medicinal, pesticidal, and timber uses.','difficulty':'easy'},
  {'id':'d281_112','subject':'da-281','question':'Bamboo belongs to which plant family?','options':['Leguminosae','Gramineae (Poaceae)','Euphorbiaceae','Rubiaceae'],'correct':1,'explanation':'Bamboo belongs to the grass family Gramineae (Poaceae). It is the fastest growing woody plant.','difficulty':'medium'},
  {'id':'d281_113','subject':'da-281','question':'Agroforestry is best defined as:','options':['Cultivation of forest trees only','A land use system combining trees with crops or livestock on the same unit of land','Growing trees in monoculture','Cultivation of medicinal plants only'],'correct':1,'explanation':'Agroforestry combines trees with crops and/or livestock on the same land unit, providing multiple benefits.','difficulty':'easy'},
  {'id':'d281_114','subject':'da-281','question':'Agrisilviculture combines:','options':['Trees + livestock','Trees + crops','Trees + fish','Trees + beekeeping'],'correct':1,'explanation':'Agrisilviculture is an agroforestry system combining trees (silvi) with agricultural crops on the same land.','difficulty':'medium'},
  {'id':'d281_115','subject':'da-281','question':'The National Forest Policy of India (1988) recommends that _____ of total land should be under forests:','options':['20%','33%','50%','10%'],'correct':1,'explanation':'The National Forest Policy 1988 recommends 33% of total land area under forest cover to maintain ecological balance.','difficulty':'medium'},
  {'id':'d281_116','subject':'da-281','question':'Ashwagandha (Withania somnifera) is primarily classified as a:','options':['Timber tree','Medicinal plant (adaptogen)','Commercial agroforestry tree','Ornamental plant'],'correct':1,'explanation':'Ashwagandha is an important medicinal plant (adaptogen) used in Ayurveda for stress relief, strength, and immunity.','difficulty':'easy'},
  {'id':'d281_117','subject':'da-281','question':'Senna (Cassia angustifolia) is used in medicine primarily as a:','options':['Wound healer','Natural laxative','Fever reducer','Blood pressure regulator'],'correct':1,'explanation':'Senna leaves and pods contain sennosides — powerful natural laxatives used in Ayurveda and modern medicine.','difficulty':'medium'},
  {'id':'d281_118','subject':'da-281','question':'Lemongrass is cultivated primarily for its:','options':['Timber','Essential oil used in cosmetics and food flavoring','Fuelwood','Fodder for cattle'],'correct':1,'explanation':'Lemongrass (Cymbopogon citratus) is grown for its aromatic essential oil used in cosmetics, food, and aromatherapy.','difficulty':'medium'},
  {'id':'d281_119','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Neem is called the village pharmacy. Reason (R): Every part of neem has medicinal, pesticidal, or agricultural uses.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Neem is the village pharmacy because its leaves, bark, seeds, and oil are used for medicine, biopesticides, and agriculture. R explains A.','difficulty':'easy'},
  {'id':'d281_120','subject':'da-281','question':'Match agroforestry systems: Col A: 1-Agrisilviculture, 2-Silvopastoral, 3-Agrosilvopastoral, 4-Aquaforestry. Col B: P-trees+fish, Q-trees+crops+livestock, R-trees+livestock, S-trees+crops. Col C: i-teak+fish ponds, ii-teak+paddy, iii-teak+sheep, iv-teak+paddy+cattle','options':['1-S-ii, 2-R-iii, 3-Q-iv, 4-P-i','1-P-i, 2-Q-iv, 3-R-iii, 4-S-ii','1-R-iii, 2-S-ii, 3-P-i, 4-Q-iv','1-Q-iv, 2-P-i, 3-S-ii, 4-R-iii'],'correct':0,'explanation':'Agrisilviculture (trees+crops=teak+paddy=ii), Silvopastoral (trees+livestock=teak+sheep=iii), Agrosilvopastoral (trees+crops+livestock=iv), Aquaforestry (trees+fish=i).','difficulty':'hard'},
  {'id':'d281_121','subject':'da-281','question':'Social forestry involves growing trees on:','options':['Reserved forests only','Village community land, roadsides, and farm boundaries for local needs','Commercial forest plantations only','Himalayan forests only'],'correct':1,'explanation':'Social forestry grows trees on community lands, roadsides, and farm boundaries to meet local needs for fuelwood, fodder, and timber.','difficulty':'easy'},
  {'id':'d281_122','subject':'da-281','question':'Non-Timber Forest Products (NTFPs) include:','options':['Logs and planks only','Bamboo, honey, medicinal plants, gums, and resins','Heavy machinery materials','Chemical fertilizers'],'correct':1,'explanation':'NTFPs are all forest products other than timber — including bamboo, honey, lac, gums, resins, medicinal plants, and wild fruits.','difficulty':'easy'},
  {'id':'d281_123','subject':'da-281','question':'The Chipko movement in India was a protest against:','options':['Industrial pollution','Commercial deforestation and tree felling in Himalayas','Wildlife poaching','Forest fires'],'correct':1,'explanation':'Chipko movement (1973, Uttarakhand) — villagers hugged trees to prevent commercial felling. It was a landmark environmental movement.','difficulty':'easy'},
  {'id':'d281_124','subject':'da-281','question':'Forest mensuration deals with:','options':['Growing trees in forests','Measurement of timber volume, tree height, diameter, and forest area','Study of forest diseases','Planting trees in degraded areas'],'correct':1,'explanation':'Forest mensuration is the branch of forestry concerned with measuring timber volumes, tree dimensions, and forest area.','difficulty':'medium'},
  {'id':'d281_125','subject':'da-281','question':'The Diameter at Breast Height (DBH) is measured at:','options':['0.5 m from ground','1.37 m from ground','2.0 m from ground','3.0 m from ground'],'correct':1,'explanation':'DBH (Diameter at Breast Height) is measured at 1.37 meters (4.5 feet) from the ground — standard in forest mensuration.','difficulty':'hard'},
  {'id':'d281_126','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Deforestation leads to increased CO2 in the atmosphere. Reason (R): Trees absorb CO2 during photosynthesis; when cut, this absorption is lost and CO2 is released.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Deforestation releases stored carbon and removes CO2-absorbing trees. R correctly explains the mechanism by which deforestation increases atmospheric CO2.','difficulty':'medium'},
  {'id':'d281_127','subject':'da-281','question':'Subabul (Leucaena leucocephala) is used for:','options':['Only timber production','Fuelwood, fodder, nitrogen fixation (multipurpose)','Only ornamental purposes','Only paper pulp'],'correct':1,'explanation':'Subabul is a multipurpose tree used for fuelwood, fodder, green manure, nitrogen fixation, and paper pulp — a key social forestry species.','difficulty':'medium'},
  {'id':'d281_128','subject':'da-281','question':'Joint Forest Management (JFM) in India aims to:','options':['Commercial timber exploitation','Involve local communities in forest protection for shared benefits','Complete protection without human use','Convert forests to agriculture'],'correct':1,'explanation':'JFM (1990) involves local communities through Village Forest Committees in forest protection and management, sharing the benefits.','difficulty':'medium'},
  {'id':'d281_129','subject':'da-281','question':'Mangrove forests are found in:','options':['Dry arid regions','Coastal saline tidal areas','Himalayan alpine zones','Dry deciduous regions'],'correct':1,'explanation':'Mangroves grow in coastal intertidal zones with saline water. They protect coastlines from erosion, cyclones, and tsunamis.','difficulty':'medium'},
  {'id':'d281_130','subject':'da-281','question':'Match medicinal plants: Col A: 1-Ashwagandha, 2-Aloe vera, 3-Senna, 4-Lemongrass. Col B: P-laxative, Q-skin healing, R-adaptogen, S-essential oil. Col C: i-Cymbopogon, ii-Cassia angustifolia, iii-Withania somnifera, iv-Aloe barbadensis','options':['1-R-iii, 2-Q-iv, 3-P-ii, 4-S-i','1-P-ii, 2-R-iii, 3-Q-iv, 4-S-i','1-S-i, 2-P-ii, 3-R-iii, 4-Q-iv','1-Q-iv, 2-S-i, 3-P-ii, 4-R-iii'],'correct':0,'explanation':'Ashwagandha (adaptogen=Withania=iii), Aloe vera (skin=Aloe barbadensis=iv), Senna (laxative=Cassia=ii), Lemongrass (essential oil=Cymbopogon=i).','difficulty':'hard'},
  {'id':'d281_131','subject':'da-281','question':'The state tree of Telangana is:','options':['Neem','Teak','Jammi tree (Prosopis cineraria)','Banyan'],'correct':2,'explanation':'The Jammi tree (Prosopis cineraria), also called Shami tree, is the State tree of Telangana, associated with Dussehra festival.','difficulty':'medium'},
  {'id':'d281_132','subject':'da-281','question':'Bamboo is called Green Gold because:','options':['It has yellow color','Of its rapid growth, versatility, and high commercial value','It stores water','It is used only for gold extraction'],'correct':1,'explanation':'Bamboo is called Green Gold because of its rapid growth, versatility, and commercial value in construction, crafts, pulp, and furniture.','difficulty':'medium'},
  {'id':'d281_133','subject':'da-281','question':'India classifies its forests (Indian Forest Act 1927) into:','options':['Reserved forests only','Reserved, protected, and unclassed forests','Commercial plantations only','Community and private forests only'],'correct':1,'explanation':'India classifies forests into Reserved Forests (strictly protected), Protected Forests, and Unclassed Forests under the Indian Forest Act 1927.','difficulty':'medium'},
  {'id':'d281_134','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Forests help prevent soil erosion. Reason (R): Tree roots bind soil particles and the canopy reduces the impact of rainfall on the soil surface.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Forests prevent soil erosion through roots binding soil and canopy intercepting raindrops. R correctly explains A.','difficulty':'easy'},
  {'id':'d281_135','subject':'da-281','question':'Lac is a forest product that is:','options':['A leaf extract from teak','A resinous secretion of lac insects on host trees','A sap extracted from eucalyptus','A root product of Acacia'],'correct':1,'explanation':'Lac is a resinous secretion produced by the lac insect (Kerria lacca) on host trees like ber, kusum, and palash. It is an important NTFP.','difficulty':'medium'},
  {'id':'d281_136','subject':'da-281','question':'Tamarind (Tamarindus indica) in forestry and food is used for:','options':['Timber and fuel only','Edible fruit, souring agent in cooking, and medicine','Fodder only','Paper pulp only'],'correct':1,'explanation':'Tamarind is used as a souring agent in cooking, in medicines, for jam/candy production. Its wood is also used for fuel and tools.','difficulty':'easy'},
  {'id':'d281_137','subject':'da-281','question':'Which is a fire resistant timber tree?','options':['Eucalyptus','Bamboo','Teak','Sal (Shorea robusta)'],'correct':3,'explanation':'Sal (Shorea robusta) is known for its fire resistance, making it valuable in forest management in fire-prone areas.','difficulty':'hard'},
  {'id':'d281_138','subject':'da-281','question':'Silvopastoral agroforestry system combines:','options':['Trees + crops','Trees + fish farming','Trees + livestock and pasture','Trees + beekeeping'],'correct':2,'explanation':'Silvopastoral combines trees (silvi) with pasture and livestock (pastoral), providing fodder, shade, and other tree products.','difficulty':'medium'},
  {'id':'d281_139','subject':'da-281','question':'The Casuarina tree is widely used for:','options':['Edible fruits','Coastal windbreaks and shelterbelts','Spice production','Gum extraction'],'correct':1,'explanation':'Casuarina (Casuarina equisetifolia) is widely used for coastal windbreaks and shelterbelts due to its fast growth and wind-tolerant nature.','difficulty':'medium'},
  {'id':'d281_140','subject':'da-281','question':'Match timber trees: Col A: 1-Teak, 2-Sandalwood, 3-Rosewood, 4-Sal. Col B: P-Dalbergia latifolia, Q-Shorea robusta, R-Tectona grandis, S-Santalum album. Col C: i-furniture/timber, ii-fire resistant, iii-perfume/incense, iv-Karnataka','options':['1-R-i, 2-S-iii, 3-P-iv, 4-Q-ii','1-S-iii, 2-R-i, 3-Q-ii, 4-P-iv','1-P-iv, 2-Q-ii, 3-R-i, 4-S-iii','1-Q-ii, 2-P-iv, 3-S-iii, 4-R-i'],'correct':0,'explanation':'Teak (Tectona grandis=i-furniture), Sandalwood (Santalum album=iii-perfume), Rosewood (Dalbergia latifolia=iv-Karnataka), Sal (Shorea robusta=ii-fire resistant).','difficulty':'hard'},
  {'id':'d281_141','subject':'da-281','question':'Which organization publishes the Global Forest Resources Assessment?','options':['UNDP','FAO','World Bank','UNEP'],'correct':1,'explanation':'FAO (Food and Agriculture Organization) publishes the Global Forest Resources Assessment periodically.','difficulty':'medium'},
  {'id':'d281_142','subject':'da-281','question':'Eucalyptus is controversial in agroforestry because:','options':['It grows very slowly','It depletes groundwater and soil nutrients despite fast growth','It is difficult to plant','It does not provide shade'],'correct':1,'explanation':'Eucalyptus is controversial because while it grows fast and yields biomass, it depletes groundwater and impoverishes soil.','difficulty':'medium'},
  {'id':'d281_143','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Eucalyptus is recommended for all agroforestry systems in India. Reason (R): Eucalyptus provides high biomass but is known to cause groundwater depletion and soil degradation.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':3,'explanation':'A is false — Eucalyptus is NOT universally recommended due to its negative environmental effects. R is true — correctly states the problems with Eucalyptus.','difficulty':'hard'},
  {'id':'d281_144','subject':'da-281','question':'The science of growing and tending to forests for human and environmental benefits is called:','options':['Dendrology','Silviculture','Ecology','Pomology'],'correct':1,'explanation':'Silviculture is the art and science of growing and tending forests — establishing, managing, and harvesting forest trees.',  'difficulty':'easy'},
  {'id':'d281_145','subject':'da-281','question':'Which forest branch is concerned with financial aspects and long-term planning?','options':['Silviculture','Dendrology','Forest management','Forest mensuration'],'correct':2,'explanation':'Forest management deals with long-term planning, financial aspects, sustained timber yield, and overall administration of forests.',  'difficulty':'medium'},
  {'id':'d281_146','subject':'da-281','question':'The primary purpose of windbreaks in agriculture is to:','options':['Provide shade to crops','Reduce wind speed and protect crops and soil from wind damage','Supply timber','Provide fuelwood'],'correct':1,'explanation':'Windbreaks (shelterbelts) are rows of trees planted perpendicular to prevailing winds to reduce wind speed, protecting crops, soil, and livestock.','difficulty':'easy'},
  {'id':'d281_147','subject':'da-281','question':'Aloe vera is primarily used for:','options':['Timber production','Burn healing, skin care, and digestive health','Soil nitrogen fixation','Windbreak protection'],'correct':1,'explanation':'Aloe vera (Aloe barbadensis) is a succulent medicinal plant widely used for treating burns, skin conditions, and digestive problems.','difficulty':'easy'},
  {'id':'d281_148','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Bamboo is the fastest growing woody plant. Reason (R): Some species of bamboo can grow up to 90 cm per day under ideal conditions.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Bamboo is indeed the fastest growing woody plant. Some tropical bamboo species can grow up to 90 cm/day. R correctly supports and explains A.','difficulty':'medium'},
  {'id':'d281_149','subject':'da-281','question':'What is the main reason forests are essential for maintaining biodiversity?','options':['Forests provide only timber','Forests provide habitat for plants, animals, microorganisms and protect ecosystems','Forests generate electricity','Forests provide only medicinal plants'],'correct':1,'explanation':'Forests are biodiversity hotspots — they provide habitat for millions of species of plants, animals, fungi, and microorganisms.',  'difficulty':'easy'},
  {'id':'d281_150','subject':'da-281','question':'Match: Col A: 1-Carbon sequestration, 2-Soil conservation, 3-Water table, 4-Biodiversity. Functions of forests. Col B: P-roots bind soil, Q-stores CO2, R-habitat, S-roots recharge groundwater. Col C: i-climate mitigation, ii-erosion prevention, iii-animal habitats, iv-well water level','options':['1-Q-i, 2-P-ii, 3-S-iv, 4-R-iii','1-P-ii, 2-Q-i, 3-R-iii, 4-S-iv','1-S-iv, 2-R-iii, 3-P-ii, 4-Q-i','1-R-iii, 2-S-iv, 3-Q-i, 4-P-ii'],'correct':0,'explanation':'Carbon sequestration (stores CO2=climate mitigation=i), Soil conservation (roots bind=erosion prevention=ii), Water table (roots recharge=well level=iv), Biodiversity (habitat=animals=iii).','difficulty':'hard'},
  {'id':'d281_151','subject':'da-281','question':'The botanical name of Indian rosewood used in furniture is:','options':['Tectona grandis','Shorea robusta','Dalbergia latifolia','Azadirachta indica'],'correct':2,'explanation':'Indian rosewood (Dalbergia latifolia) is a premium timber tree native to peninsular India, especially Karnataka, used for high-quality furniture.','difficulty':'medium'},
  {'id':'d281_152','subject':'da-281','question':'Forests classified as Reserved Forests in India are:','options':['Open for all uses','Strictly protected with all activities restricted unless permitted','Used only for tribal people','Available for commercial logging'],'correct':1,'explanation':'Reserved Forests are the most strictly protected category under the Indian Forest Act 1927 — all activities are restricted unless specifically permitted.',  'difficulty':'medium'},
  {'id':'d281_153','subject':'da-281','question':'Which tree is specifically mentioned in Indian scriptures and used during Dussehra festival?','options':['Neem','Teak','Jammi tree (Prosopis cineraria)','Banyan'],'correct':2,'explanation':'The Jammi tree (Prosopis cineraria) is worshipped during Vijayadasami (Dussehra) in Telangana and Andhra Pradesh — it is the state tree of Telangana.','difficulty':'medium'},
  {'id':'d281_154','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Social forestry aims to grow trees for the benefit of local communities. Reason (R): Social forestry focuses only on commercial timber production in reserved forests.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':2,'explanation':'A is true — social forestry benefits local communities. R is false — social forestry focuses on community land, not reserved forests, and not just for commercial timber.',  'difficulty':'medium'},
  {'id':'d281_155','subject':'da-281','question':'Forest mensuration tool used to measure diameter of a standing tree is:','options':['Hypsometer','Biltmore stick or diameter tape','Rangefinder','Compass'],'correct':1,'explanation':'A Biltmore stick or diameter tape is used to measure the diameter (girth) of standing trees in forest mensuration.',  'difficulty':'hard'},
  {'id':'d281_156','subject':'da-281','question':'What is the botanical name of sandalwood?','options':['Tectona grandis','Santalum album','Shorea robusta','Dalbergia latifolia'],'correct':1,'explanation':'Sandalwood (Santalum album) is a fragrant tropical tree native to India, used for essential oil, incense, and carving.',  'difficulty':'medium'},
  {'id':'d281_157','subject':'da-281','question':'Aquaforestry is an agroforestry system combining:','options':['Trees + livestock','Trees + crops','Trees + fish or aquatic organisms','Trees + medicinal plants'],'correct':2,'explanation':'Aquaforestry combines trees with fish farming or aquatic organisms — a system practiced in coastal and riparian areas.',  'difficulty':'medium'},
  {'id':'d281_158','subject':'da-281','question':'The primary cause of deforestation in India is:','options':['Natural forest fires only','Agricultural expansion, urbanization, and commercial timber extraction','Climate change only','Wildlife damage'],'correct':1,'explanation':'The major causes of deforestation in India are agricultural expansion, urbanization, commercial timber extraction, and fuelwood collection.',  'difficulty':'easy'},
  {'id':'d281_159','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Agroforestry systems improve farm income and environmental sustainability simultaneously. Reason (R): Combining trees with crops or livestock provides multiple products and ecological services while using land more efficiently.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Agroforestry provides timber, fruits, fodder, and ecological services from the same land, improving income and sustainability. R correctly explains A.',  'difficulty':'medium'},
  {'id':'d281_160','subject':'da-281','question':'Match forest products: Col A: 1-Timber, 2-Lac, 3-Bamboo, 4-Honey. Col B: P-NTFP from insects, Q-NTFP from grass family, R-wood for construction, S-NTFP from bees. Col C: i-furniture material, ii-insects on trees, iii-Gramineae family product, iv-beehive product','options':['1-R-i, 2-P-ii, 3-Q-iii, 4-S-iv','1-P-ii, 2-Q-iii, 3-S-iv, 4-R-i','1-Q-iii, 2-S-iv, 3-R-i, 4-P-ii','1-S-iv, 2-R-i, 3-P-ii, 4-Q-iii'],'correct':0,'explanation':'Timber (wood for construction=furniture=i), Lac (NTFP from insects=trees=ii), Bamboo (Gramineae=iii), Honey (NTFP from bees=iv).','difficulty':'hard'},
  {'id':'d281_161','subject':'da-281','question':'The tree known as Kalpavriksha or tree of heaven due to multiple uses is:','options':['Neem','Coconut','Bamboo','Teak'],'correct':1,'explanation':'Coconut (Cocos nucifera) is called Kalpavriksha (tree that fulfills wishes) because every part — fruit, leaves, shell, trunk — is useful.',  'difficulty':'medium'},
  {'id':'d281_162','subject':'da-281','question':'Afforestation means:','options':['Destroying existing forests','Planting trees on land that was previously forested (reforestation)','Planting trees on land that never had forests','Clearing forests for agriculture'],'correct':2,'explanation':'Afforestation is establishing a forest on land that was not previously forested. Reforestation specifically refers to restoring felled or degraded forest areas.',  'difficulty':'medium'},
  {'id':'d281_163','subject':'da-281','question':'India\'s target for forest cover under the Paris Agreement (Nationally Determined Contributions) is:','options':['2.5 to 3 billion tonnes additional carbon sink through forests','1 billion tonnes additional carbon sink','5 billion tonnes additional carbon sink','0.5 billion tonnes additional carbon sink'],'correct':0,'explanation':'India committed to create additional carbon sink of 2.5 to 3 billion tonnes CO2 equivalent through forest and tree cover by 2030 in its NDCs.',  'difficulty':'hard'},
  {'id':'d281_164','subject':'da-281','question':'Which of the following statements about teak is correct?','options':['Teak grows best in wet tropical conditions with waterlogged soil','Teak is a deciduous tree native to South and Southeast Asia with high timber value','Teak belongs to the grass family','Teak is an evergreen tree'],'correct':1,'explanation':'Teak (Tectona grandis) is a deciduous hardwood native to South and Southeast Asia, highly valued for its durability and resistance to decay.',  'difficulty':'medium'},
  {'id':'d281_165','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Bamboo is considered a grass, not a tree. Reason (R): Bamboo belongs to the family Gramineae (Poaceae) and has hollow, jointed stems like other grasses.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Bamboo is botanically a grass (Gramineae/Poaceae), not a tree. R correctly explains this through its family classification and stem structure.',  'difficulty':'medium'},
  {'id':'d281_166','subject':'da-281','question':'Which part of aloe vera is used medicinally?','options':['Root only','Bark only','Fleshy inner leaf gel','Seeds only'],'correct':2,'explanation':'The inner leaf gel of aloe vera contains active compounds (aloe-emodin, acemannan) used for skin healing, burns, and digestive health.',  'difficulty':'easy'},
  {'id':'d281_167','subject':'da-281','question':'The Sundarbans is the world\'s largest:','options':['Tropical wet evergreen forest','Mangrove forest','Thorn forest','Dry deciduous forest'],'correct':1,'explanation':'The Sundarbans (India-Bangladesh border) is the world\'s largest mangrove forest, a UNESCO World Heritage Site home to the Royal Bengal Tiger.',  'difficulty':'easy'},
  {'id':'d281_168','subject':'da-281','question':'Nitrogen fixing trees used in agroforestry include:','options':['Teak and sandalwood','Subabul (Leucaena) and Acacia species','Bamboo and eucalyptus','Neem and tamarind'],'correct':1,'explanation':'Subabul (Leucaena leucocephala) and Acacia species form symbiotic relationships with Rhizobium bacteria to fix atmospheric nitrogen.',  'difficulty':'medium'},
  {'id':'d281_169','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): India is a mega-biodiversity country. Reason (R): India contains about 7-8% of the world\'s recorded species despite having only 2.4% of the world\'s land area.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'India is mega-diverse with 7-8% of world\'s species in 2.4% of land area, making it one of the 17 megadiverse countries. R correctly explains A.',  'difficulty':'medium'},
  {'id':'d281_170','subject':'da-281','question':'Match: Col A: 1-Silviculture, 2-Forest mensuration, 3-Dendrology, 4-Forest management. Col B: P-tree identification, Q-financial planning, R-tree establishment/growth, S-volume measurement. Col C: i-growth rings, ii-yield table, iii-thinning operations, iv-forest working plan','options':['1-R-iii, 2-S-ii, 3-P-i, 4-Q-iv','1-P-i, 2-Q-iv, 3-R-iii, 4-S-ii','1-S-ii, 2-R-iii, 3-Q-iv, 4-P-i','1-Q-iv, 2-P-i, 3-S-ii, 4-R-iii'],'correct':0,'explanation':'Silviculture (establishment/growth=thinning=iii), Forest mensuration (volume=yield table=ii), Dendrology (tree ID=growth rings=i), Forest management (planning=working plan=iv).','difficulty':'hard'},
  {'id':'d281_171','subject':'da-281','question':'What is the main active compound in neem that makes it a biopesticide?','options':['Curcumin','Azadirachtin','Quinine','Tannin'],'correct':1,'explanation':'Azadirachtin is the main active compound in neem seeds that acts as a powerful insect repellent, antifeedant, and biopesticide.',  'difficulty':'hard'},
  {'id':'d281_172','subject':'da-281','question':'Farm forestry refers to:','options':['Growing trees only in forest departments','Growing trees on private farm land by farmers for economic benefits','Growing trees only for wildlife','Only planting fruit trees'],'correct':1,'explanation':'Farm forestry is growing trees on private farm land by farmers — combining timber, fodder, fruit trees with agriculture for additional income.',  'difficulty':'easy'},
  {'id':'d281_173','subject':'da-281','question':'Eucalyptus was introduced to India primarily from:','options':['USA','Africa','Australia','Brazil'],'correct':2,'explanation':'Eucalyptus was introduced to India from Australia in the late 19th century, initially for paper pulp production and fuel requirements.',  'difficulty':'medium'},
  {'id':'d281_174','subject':'da-281','question':'The term agroforestry was coined by:','options':['FAO in 1960','ICRAF (International Centre for Research in Agroforestry) in the 1970s','Indian Forest Act 1927','National Forest Policy 1952'],'correct':1,'explanation':'The term agroforestry was formally defined and popularized by ICRAF (now World Agroforestry Centre) in the 1970s.',  'difficulty':'hard'},
  {'id':'d281_175','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): The Chipko movement was initiated by women. Reason (R): Women in Uttarakhand hills were most affected by deforestation — losing fuelwood, fodder, and water sources.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Chipko was largely women-led because women suffer most from deforestation (collecting fuelwood, water, fodder). R correctly explains A.',  'difficulty':'medium'},
  {'id':'d281_176','subject':'da-281','question':'Which state has the highest forest cover in India?','options':['Madhya Pradesh','Maharashtra','Arunachal Pradesh','Chhattisgarh'],'correct':0,'explanation':'Madhya Pradesh has the highest total forest cover in India (77,414 sq km) as per Forest Survey of India reports.',  'difficulty':'medium'},
  {'id':'d281_177','subject':'da-281','question':'The main function of roots in preventing soil erosion is:','options':['Absorbing sunlight','Binding soil particles and increasing infiltration','Producing oxygen','Releasing nutrients'],'correct':1,'explanation':'Tree roots bind soil particles, create channels for water infiltration, and reduce surface runoff, preventing soil erosion.',  'difficulty':'easy'},
  {'id':'d281_178','subject':'da-281','question':'Match NTFP types: Col A: 1-Gum/Resin, 2-Lac, 3-Honey, 4-Medicinal plant. Col B: P-insect product, Q-bee product, R-plant exudate, S-herbal product. Col C: i-Ashwagandha, ii-Kerria lacca secretion, iii-Acacia gum, iv-honeycomb','options':['1-R-iii, 2-P-ii, 3-Q-iv, 4-S-i','1-P-ii, 2-Q-iv, 3-R-iii, 4-S-i','1-S-i, 2-R-iii, 3-P-ii, 4-Q-iv','1-Q-iv, 2-S-i, 3-P-ii, 4-R-iii'],'correct':0,'explanation':'Gum/Resin (plant exudate=Acacia gum=iii), Lac (insect secretion=Kerria lacca=ii), Honey (bee product=honeycomb=iv), Medicinal (herbal=Ashwagandha=i).','difficulty':'hard'},
  {'id':'d281_179','subject':'da-281','question':'The Indian Forest Act that governs forest management in India was enacted in:','options':['1952','1927','1972','1988'],'correct':1,'explanation':'The Indian Forest Act 1927 is the primary legislation governing forest management, reserved forests, and timber transport in India.',  'difficulty':'medium'},
  {'id':'d281_180','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Forest management aims for sustained yield from forests. Reason (R): Sustained yield means harvesting forest products at a rate that allows forests to regenerate, ensuring permanent forest productivity.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Sustained yield is a core principle of forest management — harvest must not exceed forest regeneration capacity. R correctly explains A.',  'difficulty':'medium'},
  {'id':'d281_181','subject':'da-281','question':'Which tree is used as the host plant for lac insects?','options':['Eucalyptus','Teak','Ber (Ziziphus mauritiana) and Palas (Butea monosperma)','Neem'],'correct':2,'explanation':'Lac insects (Kerria lacca) thrive on host trees like ber (Ziziphus mauritiana), kusum, and palas (Butea monosperma) to produce lac.',  'difficulty':'hard'},
  {'id':'d281_182','subject':'da-281','question':'Which of the following is NOT a medicinal plant?','options':['Ashwagandha','Aloe vera','Senna','Eucalyptus (timber)'],'correct':3,'explanation':'Eucalyptus is primarily grown for timber, pulp, and its oil (minor medicinal use), but it is not classified as a primary medicinal plant like the others listed.',  'difficulty':'medium'},
  {'id':'d281_183','subject':'da-281','question':'The main products from bamboo include:','options':['Only furniture','Construction, crafts, paper pulp, food (bamboo shoots), and biofuel','Only food','Only paper'],'correct':1,'explanation':'Bamboo is a versatile green material used for construction, furniture, handicrafts, paper pulp, bamboo shoots (food), and bioenergy.',  'difficulty':'easy'},
  {'id':'d281_184','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Teak is one of the most commercially valuable timber species in India. Reason (R): Teak wood is highly durable, resistant to decay and termites, making it ideal for furniture, shipbuilding, and flooring.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Teak is commercially valuable. R correctly explains why — its durability, decay resistance, and termite resistance make it ideal for many applications.',  'difficulty':'easy'},
  {'id':'d281_185','subject':'da-281','question':'The Vana Mahotsava (Festival of Trees) in India was initiated to promote:','options':['Wildlife protection','Tree planting and afforestation across India','Forest fire control','Timber trade'],'correct':1,'explanation':'Vana Mahotsava was started in 1950 by K.M. Munshi to promote large-scale tree planting across India. It is celebrated every July.',  'difficulty':'easy'},
  {'id':'d281_186','subject':'da-281','question':'Which forest type is found in the Western Ghats and Northeast India with rainfall over 200 cm?','options':['Tropical dry deciduous','Thorn forest','Tropical wet evergreen','Mangrove forest'],'correct':2,'explanation':'Tropical wet evergreen forests (shola forests) are found in Western Ghats and Northeast India where annual rainfall exceeds 200 cm.',  'difficulty':'medium'},
  {'id':'d281_187','subject':'da-281','question':'The Forest Survey of India (FSI) publishes the State of Forest Report every:','options':['Year','2 years','5 years','10 years'],'correct':1,'explanation':'The Forest Survey of India (FSI), Dehradun, publishes the India State of Forest Report (ISFR) every 2 years, assessing forest cover changes.',  'difficulty':'medium'},
  {'id':'d281_188','subject':'da-281','question':'Match branches of forestry: Col A: 1-Silviculture, 2-Dendrology, 3-Forest mensuration, 4-Agroforestry. Col B: P-tree study, Q-tree+crop system, R-timber measurement, S-forest growth control. Col C: i-yield tables, ii-thinning, iii-wood anatomy, iv-alley cropping','options':['1-S-ii, 2-P-iii, 3-R-i, 4-Q-iv','1-P-iii, 2-R-i, 3-Q-iv, 4-S-ii','1-R-i, 2-Q-iv, 3-P-iii, 4-S-ii','1-Q-iv, 2-S-ii, 3-P-iii, 4-R-i'],'correct':0,'explanation':'Silviculture (forest growth=thinning=ii), Dendrology (tree study=wood anatomy=iii), Forest mensuration (measurement=yield tables=i), Agroforestry (tree+crop=alley cropping=iv).','difficulty':'hard'},
  {'id':'d281_189','subject':'da-281','question':'Why is forest cover important for watershed management?','options':['Forests only produce timber','Forests reduce surface runoff, promote groundwater recharge, and regulate stream flow','Forests only provide shade','Forests block rainfall'],'correct':1,'explanation':'Forests in watersheds reduce surface runoff, increase groundwater recharge, regulate stream flow, and prevent flooding and droughts.',  'difficulty':'medium'},
  {'id':'d281_190','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Medicinal plants are an important component of forest wealth. Reason (R): About 80% of the world\'s population depends on plant-based medicines for primary healthcare.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Medicinal plants are crucial forest resources. R (WHO statistic) correctly explains their importance — most of humanity relies on plant medicines.',  'difficulty':'medium'},
  {'id':'d281_191','subject':'da-281','question':'Acacia nilotica (babul tree) is primarily used for:','options':['Edible fruits only','Gum arabic, fuelwood, fodder, and tannin extraction','Timber only','Ornamental purposes'],'correct':1,'explanation':'Acacia nilotica (babul) produces gum arabic, provides fuelwood, fodder, tannin for leather industry, and is used in social forestry.',  'difficulty':'medium'},
  {'id':'d281_192','subject':'da-281','question':'The correct sequence of Forest Policy evolution in India is:','options':['1894 → 1952 → 1988','1952 → 1894 → 1988','1988 → 1952 → 1894','1927 → 1952 → 1994'],'correct':0,'explanation':'India\'s forest policies: 1894 (First Forest Policy under British), 1952 (Independent India\'s first policy), 1988 (Current National Forest Policy).',  'difficulty':'hard'},
  {'id':'d281_193','subject':'da-281','question':'Which is the fastest growing tree species used in commercial forestry?','options':['Teak','Sandalwood','Eucalyptus and Casuarina','Sal'],'correct':2,'explanation':'Eucalyptus and Casuarina are among the fastest growing tree species (3-5 year rotation), widely used in commercial/farm forestry for fuelwood and pulpwood.',  'difficulty':'medium'},
  {'id':'d281_194','subject':'da-281','question':'Neem seeds contain neem oil used as a biopesticide; the main active compound is:','options':['Curcumin','Azadirachtin','Allicin','Quinine'],'correct':1,'explanation':'Azadirachtin is the primary active compound in neem seeds responsible for its insecticidal, antifeedant, and growth disruption properties.',  'difficulty':'hard'},
  {'id':'d281_195','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Alley cropping is a type of agroforestry. Reason (R): In alley cropping, food crops are grown in alleys between rows of trees or shrubs, benefiting from shade, fallen leaves (mulch), and root competition being limited.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Alley cropping is an agroforestry system where crops are planted between rows of trees. R correctly describes the system and its benefits.',  'difficulty':'medium'},
  {'id':'d281_196','subject':'da-281','question':'The primary role of forests in the global carbon cycle is:','options':['Carbon emitters','Carbon sinks that absorb CO2 through photosynthesis','Carbon neutral (no net effect)','Carbon producers only'],'correct':1,'explanation':'Forests are major carbon sinks — absorbing CO2 through photosynthesis and storing it in biomass and soil, helping regulate global climate.',  'difficulty':'easy'},
  {'id':'d281_197','subject':'da-281','question':'Which Indian forest region is known as the Lungs of the Earth due to oxygen production?','options':['Western Ghats forests','Amazon Rainforest in South America (global reference)','Sundarbans mangroves','Thar desert scrub forests'],'correct':0,'explanation':'The Western Ghats are among the world\'s biodiversity hotspots and major oxygen producers. At global scale, the Amazon is called lungs, but in Indian context, Western Ghats are highlighted.',  'difficulty':'medium'},
  {'id':'d281_198','subject':'da-281','question':'Match forest types to distribution: Col A: 1-Mangrove, 2-Alpine forest, 3-Dry thorn, 4-Tropical evergreen. Col B: P-Western Ghats, Q-Himalayas, R-Rajasthan, S-Sundarbans/coastal. Col C: i-above 3000m altitude, ii-rainfall >200cm, iii-saline tidal zone, iv-rainfall <75cm','options':['1-S-iii, 2-Q-i, 3-R-iv, 4-P-ii','1-Q-i, 2-R-iv, 3-S-iii, 4-P-ii','1-P-ii, 2-S-iii, 3-Q-i, 4-R-iv','1-R-iv, 2-P-ii, 3-Q-i, 4-S-iii'],'correct':0,'explanation':'Mangrove (saline tidal=Sundarbans=iii), Alpine (>3000m=Himalayas=i), Dry thorn (<75cm=Rajasthan=iv), Tropical evergreen (>200cm=Western Ghats=ii).','difficulty':'hard'},
  {'id':'d281_199','subject':'da-281','question':'ASSERTION-REASON: Assertion (A): Joint Forest Management (JFM) was introduced in India in 1990. Reason (R): JFM was introduced to recognize that top-down forest management alone had failed to protect forests and communities needed to be partners.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'JFM was introduced in 1990 recognizing the failure of centralized management. Community involvement through Village Forest Committees improved forest protection. R explains A.',  'difficulty':'medium'},
  {'id':'d281_200','subject':'da-281','question':'What percentage of India\'s medicinal plants are sourced from forests?','options':['10%','25%','70%','95%'],'correct':2,'explanation':'Approximately 70% of India\'s medicinal plants used in traditional medicine (Ayurveda, Siddha, Unani) are sourced from forests and forest-adjacent areas.',  'difficulty':'hard'},
]

LQ = shuffle_q(LQ)
CQ = shuffle_q(CQ)

append_to_file(os.path.join(BASE, 'da-281-lectures.ts'), LQ, True)
append_to_file(os.path.join(BASE, 'da-281.ts'), CQ, False)
print("DA-281 done!")
