"""Add 100 new lecture questions and 100 combined questions for DA-263 English Communication."""
import sys, random
sys.stdout.reconfigure(encoding='utf-8')

BASE = r"C:\Users\bioas\Agricet Mock Test Series\src\data\questions"

def shuffle_q(questions):
    for q in questions:
        opts = q['options'][:]
        ct = opts[q['correct']]
        seed = abs(hash(repr(opts))) % (2**31)
        rng = random.Random(seed)
        rng.shuffle(opts)
        q['options'] = opts
        q['correct'] = opts.index(ct)
    return questions

def append_to_file(fpath, questions, is_lecture):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    content = content.rstrip()
    if content.endswith('];'):
        content = content[:-2].rstrip()
    parts = []
    for q in questions:
        opts_str = ', '.join('"' + o.replace('\\', '\\\\').replace('"', '\\"') + '"' for o in q['options'])
        qt = q['question'].replace('\\', '\\\\').replace('"', '\\"')
        et = q['explanation'].replace('\\', '\\\\').replace('"', '\\"')
        if is_lecture:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject'] + '", lecture: "' + q['lecture']
                 + '", lectureNo: ' + str(q['lectureNo']) + ',\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        else:
            s = ('  {\n    id: "' + q['id'] + '", subject: "' + q['subject']
                 + '",\n    question: "' + qt
                 + '",\n    options: [' + opts_str + '],\n    correct: ' + str(q['correct'])
                 + ',\n    explanation: "' + et + '",\n    difficulty: "' + q['difficulty'] + '"\n  }')
        parts.append(s)
    new_content = content + ',\n' + ',\n'.join(parts) + '\n\n];'
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"  Appended {len(questions)} questions to {fpath.split(chr(92))[-1]}")

# ── 100 new lecture questions ──────────────────────────────────────────────────
LQ = [
  {'id':'d263l_101','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Which tense is used in: She has been studying agriculture for three years?',
   'options':['Present Perfect Continuous','Past Perfect Continuous','Present Continuous','Present Perfect'],
   'correct':0,'explanation':'Present Perfect Continuous (has/have + been + V-ing) shows an action started in the past and still continuing.',
   'difficulty':'medium'},
  {'id':'d263l_102','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Identify the type of sentence: What a beautiful harvest!',
   'options':['Interrogative','Exclamatory','Imperative','Declarative'],
   'correct':1,'explanation':'Exclamatory sentences express strong emotion and end with an exclamation mark.',
   'difficulty':'easy'},
  {'id':'d263l_103','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Correct passive voice of: The farmer waters the plants daily.',
   'options':['The plants were watered daily by the farmer.','The plants are watered daily by the farmer.','The plants have been watered daily by the farmer.','The plants will be watered daily by the farmer.'],
   'correct':1,'explanation':'Simple present active to passive: is/are + past participle. The plants are watered daily by the farmer.',
   'difficulty':'medium'},
  {'id':'d263l_104','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Which word is an abstract noun?',
   'options':['Honesty','River','Book','Farmer'],
   'correct':0,'explanation':'Abstract nouns name qualities or states that cannot be physically perceived. Honesty is an abstract noun.',
   'difficulty':'easy'},
  {'id':'d263l_105','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'In: The crop which was damaged by floods was paddy — the clause which was damaged by floods is a:',
   'options':['Noun clause','Adverb clause','Adjective clause','Independent clause'],
   'correct':2,'explanation':'An adjective clause modifies a noun. Which was damaged by floods modifies crop — it is a relative clause.',
   'difficulty':'medium'},
  {'id':'d263l_106','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Select the correctly punctuated sentence in indirect speech:',
   'options':['Ram said that he will come tomorrow.','Ram said, he will come tomorrow.','Ram said that he would come tomorrow.','Ram said; that he would come tomorrow.'],
   'correct':2,'explanation':'In reported speech, will changes to would. No comma is needed before that in indirect speech.',
   'difficulty':'medium'},
  {'id':'d263l_107','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'The word agriculture is a _____ noun.',
   'options':['Proper','Collective','Abstract','Common'],
   'correct':3,'explanation':'A common noun refers to a general class of things. Agriculture is a common noun.',
   'difficulty':'easy'},
  {'id':'d263l_108','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Which sentence uses the subjunctive mood correctly?',
   'options':['I wish I was a better farmer.','I wish I am a better farmer.','I wish I were a better farmer.','I wish I will be a better farmer.'],
   'correct':2,'explanation':'Subjunctive mood uses were (not was) for all persons when expressing a wish or hypothetical situation.',
   'difficulty':'hard'},
  {'id':'d263l_109','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'ASSERTION-REASON: Assertion (A): Collective nouns take a singular verb when the group acts as one unit. Reason (R): A collective noun names a group of people, animals, or things.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'R correctly defines collective nouns and explains why they can take singular verbs when acting as a unified body.',
   'difficulty':'medium'},
  {'id':'d263l_110','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Match: Col A: 1-Personal, 2-Reflexive, 3-Relative, 4-Demonstrative. Col B: P-himself, Q-who, R-this, S-they. Col C: i-refers back to subject, ii-connects clauses, iii-points to thing, iv-replaces noun',
   'options':['1-S-iv, 2-P-i, 3-Q-ii, 4-R-iii','1-P-i, 2-Q-ii, 3-R-iii, 4-S-iv','1-S-ii, 2-Q-i, 3-P-iii, 4-R-iv','1-R-iii, 2-S-iv, 3-P-i, 4-Q-ii'],
   'correct':0,'explanation':'Personal (they=iv), Reflexive (himself=i), Relative (who=ii), Demonstrative (this=iii-points to thing).',
   'difficulty':'hard'},
  {'id':'d263l_111','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'The plural of ox is:',
   'options':['Oxes','Oxen','Ox','Oxs'],
   'correct':1,'explanation':'Ox forms its plural as oxen — an irregular plural that does not follow the standard -s rule.',
   'difficulty':'easy'},
  {'id':'d263l_112','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Identify the error in: The committee have decided to postpone their meeting.',
   'options':['No error — committee is always plural','committee should be followed by has as it acts as one body','decided should be decide','their should be its'],
   'correct':1,'explanation':'When a collective noun acts as a single unit, it takes a singular verb. The committee has decided is correct.',
   'difficulty':'medium'},
  {'id':'d263l_113','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Which is a transitive verb in: The extension worker taught the farmers new techniques?',
   'options':['extension','farmers','taught','new'],
   'correct':2,'explanation':'A transitive verb takes a direct object. Taught takes farmers and new techniques as objects.',
   'difficulty':'medium'},
  {'id':'d263l_114','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'The degrees of comparison of good are:',
   'options':['Good, gooder, goodest','Good, better, best','Good, more good, most good','Good, weller, wellest'],
   'correct':1,'explanation':'Good has irregular degrees of comparison: positive=good, comparative=better, superlative=best.',
   'difficulty':'easy'},
  {'id':'d263l_115','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'In: He works hard but earns little, the word but is a:',
   'options':['Preposition','Adverb','Coordinating conjunction','Subordinating conjunction'],
   'correct':2,'explanation':'But is a coordinating conjunction (FANBOYS) that joins two independent clauses of equal rank.',
   'difficulty':'medium'},
  {'id':'d263l_116','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Choose the correct article: _____ honest farmer never cheats.',
   'options':['A','An','The','No article needed'],
   'correct':1,'explanation':'An is used before words starting with a vowel sound. Honest starts with a silent h, so the vowel sound requires an.',
   'difficulty':'medium'},
  {'id':'d263l_117','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Which sentence is in Past Perfect tense?',
   'options':['He was eating when I arrived.','He ate before I arrived.','He had eaten before I arrived.','He has eaten already.'],
   'correct':2,'explanation':'Past Perfect (had + past participle) shows an action completed before another past action.',
   'difficulty':'medium'},
  {'id':'d263l_118','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'The figure of speech in: The wind whispered through the trees is:',
   'options':['Metaphor','Simile','Personification','Alliteration'],
   'correct':2,'explanation':'Personification gives human qualities to non-human things. The wind cannot literally whisper.',
   'difficulty':'medium'},
  {'id':'d263l_119','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'ASSERTION-REASON: Assertion (A): In English, adjectives do not change form for singular/plural nouns. Reason (R): Unlike verbs, adjectives in English are invariable in number.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'English adjectives remain unchanged regardless of number (a tall tree, tall trees). R correctly explains this property.',
   'difficulty':'medium'},
  {'id':'d263l_120','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Match verb forms: Col A: 1-V1, 2-V2, 3-V3, 4-V1+ing. Col B: P-Past tense, Q-Past participle, R-Present participle, S-Base form. Col C: i-eaten, ii-eats, iii-eating, iv-ate',
   'options':['1-S-ii, 2-P-iv, 3-Q-i, 4-R-iii','1-P-iv, 2-Q-i, 3-R-iii, 4-S-ii','1-S-iii, 2-P-i, 3-Q-iv, 4-R-ii','1-R-iii, 2-S-ii, 3-P-iv, 4-Q-i'],
   'correct':0,'explanation':'V1 (base: eats=ii), V2 (past: ate=iv), V3 (past participle: eaten=i), V1+ing (present participle: eating=iii).',
   'difficulty':'hard'},
  {'id':'d263l_121','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The synonym of arid is:',
   'options':['Fertile','Humid','Dry','Lush'],
   'correct':2,'explanation':'Arid means extremely dry. Dry land regions with very little rainfall are called arid zones.',
   'difficulty':'easy'},
  {'id':'d263l_122','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The antonym of transparent is:',
   'options':['Clear','Opaque','Visible','Bright'],
   'correct':1,'explanation':'Opaque means not transparent — it does not allow light to pass through.',
   'difficulty':'easy'},
  {'id':'d263l_123','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'In reading comprehension, skimming means:',
   'options':['Reading every word carefully','Reading to find specific information','Reading quickly to get the main idea','Reading aloud'],
   'correct':2,'explanation':'Skimming is reading quickly to get the gist or main idea of a text without reading every word.',
   'difficulty':'easy'},
  {'id':'d263l_124','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Identify the correctly spelled word:',
   'options':['Recieve','Achieve','Beleive','Decieve'],
   'correct':1,'explanation':'The rule i before e except after c applies. Achieve is correctly spelled. Receive follows the exception.',
   'difficulty':'medium'},
  {'id':'d263l_125','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The phrase once in a blue moon means:',
   'options':['During full moon nights','Very rarely','Every month','During festivals'],
   'correct':1,'explanation':'Once in a blue moon is an idiom meaning something that happens very rarely or almost never.',
   'difficulty':'medium'},
  {'id':'d263l_126','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Correct indirect speech for: The teacher said, Work hard.',
   'options':['The teacher said to work hard.','The teacher told to work hard.','The teacher advised to work hard.','The teacher said that work hard.'],
   'correct':0,'explanation':'For imperative sentences in indirect speech: said + to + infinitive. The teacher said to work hard is correct.',
   'difficulty':'medium'},
  {'id':'d263l_127','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Which sentence uses affect and effect correctly?',
   'options':['The drought will effect the crops badly.','The drought will affect the crops badly.','The drought will effecting the crops.','The drought has effect on crops.'],
   'correct':1,'explanation':'Affect (verb) = to influence. Effect (noun) = result. Will affect the crops is the correct usage.',
   'difficulty':'medium'},
  {'id':'d263l_128','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'ASSERTION-REASON: Assertion (A): Scanning is used to look for specific information in a text. Reason (R): Scanning involves reading every sentence slowly and carefully.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':2,'explanation':'A is true — scanning searches for specific facts. R is false — scanning is quick targeted reading, not slow careful reading.',
   'difficulty':'medium'},
  {'id':'d263l_129','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Match communication types: Col A: 1-Verbal, 2-Non-verbal, 3-Formal, 4-Informal. Col B: P-official channel, Q-body language, R-casual talk, S-words. Col C: i-gestures, ii-official letter, iii-friend talk, iv-speech',
   'options':['1-S-iv, 2-Q-i, 3-P-ii, 4-R-iii','1-P-ii, 2-S-iv, 3-Q-i, 4-R-iii','1-Q-i, 2-S-iv, 3-R-iii, 4-P-ii','1-R-iii, 2-P-ii, 3-S-iv, 4-Q-i'],
   'correct':0,'explanation':'Verbal (words: speech=iv), Non-verbal (body language=gestures=i), Formal (official=letter=ii), Informal (casual=friend talk=iii).',
   'difficulty':'hard'},
  {'id':'d263l_130','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'A formal letter written to an organization asking for a job is called a:',
   'options':['Notice','Circular','Application letter','Memorandum'],
   'correct':2,'explanation':'An application letter is written formally to apply for a job or position in an organization.',
   'difficulty':'easy'},
  {'id':'d263l_131','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Which part of a formal letter contains the main message?',
   'options':['Salutation','Body','Date','Complimentary close'],
   'correct':1,'explanation':'The body of a letter contains the main content and purpose of the communication.',
   'difficulty':'easy'},
  {'id':'d263l_132','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The abbreviation etc. stands for:',
   'options':['et cetera meaning and so on','example given','et al. meaning and others','external connection'],
   'correct':0,'explanation':'Etc. is from Latin et cetera meaning and so forth or and other things of the same kind.',
   'difficulty':'easy'},
  {'id':'d263l_133','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'In a report, the section that summarizes findings and gives recommendations is called:',
   'options':['Introduction','Methodology','Conclusion','Bibliography'],
   'correct':2,'explanation':'The conclusion section summarizes key findings and often includes recommendations for action.',
   'difficulty':'easy'},
  {'id':'d263l_134','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Which is a feature of good technical writing?',
   'options':['Use of complex jargon','Ambiguous language','Clarity and precision','Long sentences'],
   'correct':2,'explanation':'Good technical writing is clear, precise, and free of ambiguity to ensure accurate communication.',
   'difficulty':'easy'},
  {'id':'d263l_135','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'What does precis writing involve?',
   'options':['Expanding a passage into a longer version','Summarizing a passage in one-third its length','Translating a passage into another language','Copying a passage verbatim'],
   'correct':1,'explanation':'Precis writing is summarizing a passage into about one-third of its original length while retaining all key ideas.',
   'difficulty':'medium'},
  {'id':'d263l_136','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The term bibliography in a report refers to:',
   'options':['List of tables','List of figures','List of sources consulted','List of abbreviations'],
   'correct':2,'explanation':'A bibliography lists all books, articles, and other sources consulted while writing a report.',
   'difficulty':'easy'},
  {'id':'d263l_137','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'In group discussion, the most important skill is:',
   'options':['Talking more than others','Active listening','Interrupting others','Using only technical terms'],
   'correct':1,'explanation':'Active listening — paying full attention and responding appropriately — is the cornerstone of effective group discussion.',
   'difficulty':'medium'},
  {'id':'d263l_138','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Choose the sentence with correct subject-verb agreement:',
   'options':['Neither of the farmers were present.','Each of the crops require water.','The quality of vegetables depend on soil.','Mathematics is a difficult subject.'],
   'correct':3,'explanation':'Names of subjects (Mathematics, Physics) are singular and take singular verbs. Mathematics is is correct.',
   'difficulty':'medium'},
  {'id':'d263l_139','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'ASSERTION-REASON: Assertion (A): A CV is longer and more detailed than a resume. Reason (R): A CV includes complete academic and professional history, while a resume is a brief summary.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Both statements are true. R correctly explains why a CV is longer — it provides complete academic and career details.',
   'difficulty':'medium'},
  {'id':'d263l_140','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Match letter types: Col A: 1-Complaint, 2-Enquiry, 3-Application, 4-Appreciation. Col B: P-seek info, Q-gratitude, R-apply for post, S-report problem. Col C: i-I wish to apply, ii-bring to your notice, iii-enquire about, iv-sincere thanks',
   'options':['1-S-ii, 2-P-iii, 3-R-i, 4-Q-iv','1-P-iii, 2-S-ii, 3-Q-iv, 4-R-i','1-R-i, 2-Q-iv, 3-P-iii, 4-S-ii','1-Q-iv, 2-R-i, 3-S-ii, 4-P-iii'],
   'correct':0,'explanation':'Complaint (report problem=bring to notice=ii), Enquiry (seek info=enquire=iii), Application (apply for=i), Appreciation (gratitude=thanks=iv).',
   'difficulty':'hard'},
  {'id':'d263l_141','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Which best defines communication?',
   'options':['One-way transmission of information','Exchange of information, ideas, or feelings between individuals','Written messages only','Use of technology to send data'],
   'correct':1,'explanation':'Communication is the process of exchanging information, ideas, thoughts, or feelings between sender and receiver.',
   'difficulty':'easy'},
  {'id':'d263l_142','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'The element that converts the message into symbols in the communication process is called:',
   'options':['Decoding','Feedback','Encoding','Channel'],
   'correct':2,'explanation':'Encoding is the process by which the sender converts the message into symbols for transmission.',
   'difficulty':'medium'},
  {'id':'d263l_143','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Noise in communication refers to:',
   'options':['Loud sounds only','Any barrier that interferes with the message','Radio static only','Volume of speech'],
   'correct':1,'explanation':'In communication theory, noise means any interference (physical, psychological, or semantic) that distorts the message.',
   'difficulty':'medium'},
  {'id':'d263l_144','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'An example of downward communication in an organization is:',
   'options':['Workers reporting problems to manager','Manager issuing instructions to workers','Workers discussing among themselves','Two managers exchanging information'],
   'correct':1,'explanation':'Downward communication flows from higher to lower levels — manager giving instructions to workers.',
   'difficulty':'medium'},
  {'id':'d263l_145','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Which is a barrier to effective communication?',
   'options':['Clear language','Active listening','Stereotyping and prejudice','Proper feedback'],
   'correct':2,'explanation':'Stereotyping and prejudice create psychological barriers that distort understanding and block effective communication.',
   'difficulty':'medium'},
  {'id':'d263l_146','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'The process by which the receiver interprets the message is called:',
   'options':['Encoding','Feedback','Channel','Decoding'],
   'correct':3,'explanation':'Decoding is the process by which the receiver translates symbols back into meaning to understand the message.',
   'difficulty':'medium'},
  {'id':'d263l_147','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Which type of communication includes gestures, facial expressions, and eye contact?',
   'options':['Written communication','Verbal communication','Non-verbal communication','Electronic communication'],
   'correct':2,'explanation':'Non-verbal communication includes gestures, facial expressions, body posture, eye contact, and touch.',
   'difficulty':'easy'},
  {'id':'d263l_148','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'The response given by the receiver to the sender message is called:',
   'options':['Encoding','Channel','Feedback','Noise'],
   'correct':2,'explanation':'Feedback is the receiver response to the sender message — it completes the communication cycle.',
   'difficulty':'easy'},
  {'id':'d263l_149','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'ASSERTION-REASON: Assertion (A): Effective communication requires feedback. Reason (R): Without feedback, the sender cannot confirm whether the message was correctly understood.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Feedback is essential to confirm message receipt and understanding. R is the correct explanation of why feedback makes communication effective.',
   'difficulty':'medium'},
  {'id':'d263l_150','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Match barriers: Col A: 1-Physical, 2-Semantic, 3-Psychological, 4-Organizational. Col B: P-attitudes, Q-distance/noise, R-hierarchy, S-language. Col C: i-prejudice, ii-jargon, iii-long command chain, iv-poor phone connection',
   'options':['1-Q-iv, 2-S-ii, 3-P-i, 4-R-iii','1-P-i, 2-Q-iv, 3-R-iii, 4-S-ii','1-S-ii, 2-P-i, 3-Q-iv, 4-R-iii','1-R-iii, 2-Q-iv, 3-S-ii, 4-P-i'],
   'correct':0,'explanation':'Physical (noise=poor phone=iv), Semantic (language=jargon=ii), Psychological (attitudes=prejudice=i), Organizational (hierarchy=long chain=iii).',
   'difficulty':'hard'},
  {'id':'d263l_151','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Choose the sentence in Future Perfect tense:',
   'options':['She will harvest the crops.','She is harvesting the crops.','She will have harvested the crops by December.','She has harvested the crops.'],
   'correct':2,'explanation':'Future Perfect (will have + past participle) expresses an action that will be completed before a specific future time.',
   'difficulty':'medium'},
  {'id':'d263l_152','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Choose the correct preposition: The crops depend _____ rainfall.',
   'options':['on','at','with','by'],
   'correct':0,'explanation':'Depend on is the correct prepositional phrase. The crops depend on rainfall is correct.',
   'difficulty':'easy'},
  {'id':'d263l_153','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Which is an example of alliteration?',
   'options':['Peter Piper picked a peck of pickled peppers.','The farmer works hard every day.','She sells vegetables at the market.','Rain, rain, go away.'],
   'correct':0,'explanation':'Alliteration is repetition of the same consonant sound at the start of nearby words. P sound repeats in Peter Piper picked.',
   'difficulty':'easy'},
  {'id':'d263l_154','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The figure of speech The crop yield was a sea of gold is an example of:',
   'options':['Simile','Metaphor','Personification','Hyperbole'],
   'correct':1,'explanation':'A metaphor directly compares two things without using like or as. The crop is being called a sea of gold.',
   'difficulty':'medium'},
  {'id':'d263l_155','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The correct meaning of burn the midnight oil is:',
   'options':['Waste energy','Work or study late at night','Cause fire hazard','Waste fuel'],
   'correct':1,'explanation':'Burn the midnight oil means to work or study very late into the night.',
   'difficulty':'medium'},
  {'id':'d263l_156','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The tone of a formal letter should be:',
   'options':['Casual and friendly','Emotional and personal','Polite, respectful, and professional','Demanding and urgent'],
   'correct':2,'explanation':'Formal letters must maintain a polite, respectful, and professional tone regardless of the purpose.',
   'difficulty':'easy'},
  {'id':'d263l_157','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'A business email must include:',
   'options':['Subject line, salutation, body, and closing','Only body text','Header image and footer only','Date and signature only'],
   'correct':0,'explanation':'A professional business email must include a clear subject line, appropriate salutation, body of message, and a closing.',
   'difficulty':'easy'},
  {'id':'d263l_158','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Which communication channel has the richest information capacity?',
   'options':['Written memo','Email','Face-to-face conversation','Bulletin board notice'],
   'correct':2,'explanation':'Face-to-face conversation is the richest channel — it combines verbal words, tone, facial expressions, and immediate feedback.',
   'difficulty':'medium'},
  {'id':'d263l_159','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Grapevine communication refers to:',
   'options':['Agricultural communication channels','Official written communication','Informal rumour-based network in organizations','Electronic mass media'],
   'correct':2,'explanation':'Grapevine communication is an informal network through which rumours and unofficial information spread quickly in organizations.',
   'difficulty':'medium'},
  {'id':'d263l_160','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'Choose the correct form: He _____ the field before the rains arrived.',
   'options':['ploughs','ploughed','has ploughed','will plough'],
   'correct':1,'explanation':'Before the rains arrived sets context in the past. Simple past ploughed is correct for a completed action.',
   'difficulty':'medium'},
  {'id':'d263l_161','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'A word that joins a noun or pronoun to other words in the sentence is a:',
   'options':['Conjunction','Interjection','Preposition','Adverb'],
   'correct':2,'explanation':'A preposition (in, on, at, by, with) links a noun or pronoun to other parts of the sentence.',
   'difficulty':'easy'},
  {'id':'d263l_162','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'The conjunction although is classified as:',
   'options':['Coordinating conjunction','Correlative conjunction','Subordinating conjunction','Compound conjunction'],
   'correct':2,'explanation':'Although introduces a subordinate (dependent) clause and is therefore a subordinating conjunction.',
   'difficulty':'medium'},
  {'id':'d263l_163','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'The word perennial when used in farming means:',
   'options':['Grown once','Lasting only one season','Growing year after year without replanting','Seasonal crop'],
   'correct':2,'explanation':'A perennial crop (sugarcane, banana, coconut) lives for more than two years, growing year after year.',
   'difficulty':'medium'},
  {'id':'d263l_164','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The process of converting spoken language into written form is called:',
   'options':['Editing','Transcription','Translation','Summarizing'],
   'correct':1,'explanation':'Transcription is the process of converting spoken or audio content into written text.',
   'difficulty':'easy'},
  {'id':'d263l_165','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'What is the purpose of a notice in official communication?',
   'options':['To provide detailed explanation of a topic','To inform a specific group about an event or decision','To seek information from an organization','To express gratitude'],
   'correct':1,'explanation':'A notice is used to officially inform a group of people about an upcoming event, meeting, or policy change.',
   'difficulty':'easy'},
  {'id':'d263l_166','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The correct salutation for a formal letter to a company is:',
   'options':['Hi there,','Dear Sir or Madam,','Hey Friend,','Respected Buddy,'],
   'correct':1,'explanation':'Dear Sir/Madam is the standard formal salutation when writing to an organization or unknown recipient.',
   'difficulty':'easy'},
  {'id':'d263l_167','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Oral presentations differ from written reports because they:',
   'options':['Contain more data','Use visual aids and allow immediate audience feedback','Are always shorter','Are less formal'],
   'correct':1,'explanation':'Oral presentations are interactive — they use visual aids and allow real-time audience questions and feedback.',
   'difficulty':'medium'},
  {'id':'d263l_168','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'ICT in agricultural communication stands for:',
   'options':['International Communication Technology','Information and Communication Technology','Integrated Communication Training','Intercultural Communication Theory'],
   'correct':1,'explanation':'ICT stands for Information and Communication Technology — tools like internet, mobile phones, and computers used in agriculture.',
   'difficulty':'easy'},
  {'id':'d263l_169','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'The word flock is a collective noun for:',
   'options':['Fish','Bees','Birds or sheep','Cattle'],
   'correct':2,'explanation':'A flock is the collective noun for birds (a flock of pigeons) or sheep (a flock of sheep).',
   'difficulty':'easy'},
  {'id':'d263l_170','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'In the phrase the golden harvest, golden functions as:',
   'options':['Adverb','Noun','Verb','Adjective'],
   'correct':3,'explanation':'Golden describes the noun harvest — it is a qualifying adjective.',
   'difficulty':'easy'},
  {'id':'d263l_171','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'ASSERTION-REASON: Assertion (A): An adverb can modify an adjective. Reason (R): Adverbs modify only verbs and cannot modify any other part of speech.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':2,'explanation':'A is true — adverbs CAN modify adjectives (e.g., very green). R is false — adverbs modify verbs, adjectives, and other adverbs.',
   'difficulty':'medium'},
  {'id':'d263l_172','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The word infer means:',
   'options':['State directly','Draw a conclusion from evidence','Disagree with','Repeat'],
   'correct':1,'explanation':'To infer is to reach a conclusion based on evidence and reasoning, not explicitly stated.',
   'difficulty':'medium'},
  {'id':'d263l_173','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The minutes of a meeting record:',
   'options':['Only the agenda items','Discussion points, decisions made, and action items','Only the names of attendees','Financial reports'],
   'correct':1,'explanation':'Minutes of a meeting are official records of discussion points, decisions taken, and action items to be followed up.',
   'difficulty':'easy'},
  {'id':'d263l_174','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Which sentence is grammatically correct?',
   'options':['Between you and I, the crop is good.','Between you and me, the crop is good.','Between you and mine, the crop is good.','Between you and myself, the crop is good.'],
   'correct':1,'explanation':'After prepositions (between, with, for, by), use objective pronouns (me, him, her). Between you and me is correct.',
   'difficulty':'medium'},
  {'id':'d263l_175','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Which is an example of horizontal communication?',
   'options':['Principal giving instructions to teachers','Teachers reporting to principal','Two teachers discussing lesson plans','Student submitting work to teacher'],
   'correct':2,'explanation':'Horizontal (lateral) communication occurs between people at the same level in an organization hierarchy.',
   'difficulty':'medium'},
  {'id':'d263l_176','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'What is a gerund?',
   'options':['A verb used as an adjective','A verb form ending in -ing used as a noun','A verb in past tense','An adverb derived from a verb'],
   'correct':1,'explanation':'A gerund is a verb form ending in -ing that functions as a noun (e.g., Farming is a noble profession).',
   'difficulty':'medium'},
  {'id':'d263l_177','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Choose the sentence with correct use of fewer vs less:',
   'options':['We have less farmers this year.','We have fewer water in the tank.','We have fewer farmers this year.','We have less problems now.'],
   'correct':2,'explanation':'Fewer is used with countable nouns (farmers), less is used with uncountable nouns (water). Fewer farmers is correct.',
   'difficulty':'medium'},
  {'id':'d263l_178','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Which is NOT a feature of effective listening?',
   'options':['Maintaining eye contact','Avoiding distractions','Interrupting to correct the speaker','Asking clarifying questions'],
   'correct':2,'explanation':'Interrupting to correct breaks the speaker flow and is not a feature of effective listening. Active listening requires holding interruptions.',
   'difficulty':'medium'},
  {'id':'d263l_179','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'ASSERTION-REASON: Assertion (A): Public speaking is primarily a one-way communication form. Reason (R): In public speaking, the speaker transmits messages to an audience with limited immediate feedback.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'In a speech the speaker talks to the audience (one-way dominant). R correctly explains why — audience feedback is limited during the speech.',
   'difficulty':'medium'},
  {'id':'d263l_180','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'The antonym of abundant is:',
   'options':['Plentiful','Scarce','Sufficient','Ample'],
   'correct':1,'explanation':'Scarce means insufficient in supply — opposite of abundant which means available in large quantities.',
   'difficulty':'easy'},
  {'id':'d263l_181','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'A memorandum (memo) is used for:',
   'options':['External business communication','Internal organizational communication','Academic correspondence','Legal contracts'],
   'correct':1,'explanation':'A memorandum is a brief written communication used internally within an organization to convey information or instructions.',
   'difficulty':'easy'},
  {'id':'d263l_182','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The primary function of the introduction in a speech is to:',
   'options':['Summarize the speech','Present supporting evidence','Gain attention and state the purpose','Give conclusions'],
   'correct':2,'explanation':'The introduction should capture audience attention, establish credibility, and clearly state the topic and purpose.',
   'difficulty':'easy'},
  {'id':'d263l_183','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Only should be placed correctly in: I ate _____ vegetables yesterday (nothing else eaten).',
   'options':['I only ate vegetables yesterday.','Only I ate vegetables yesterday.','I ate only vegetables yesterday.','I ate vegetables only yesterday.'],
   'correct':2,'explanation':'Only should be placed immediately before the word it modifies. I ate only vegetables means nothing else was eaten.',
   'difficulty':'hard'},
  {'id':'d263l_184','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Parallelism in writing means:',
   'options':['Writing two opposing ideas','Using the same grammatical structure for similar elements','Comparing two subjects directly','Writing long parallel paragraphs'],
   'correct':1,'explanation':'Parallelism maintains consistent grammatical form in lists. The farmer ploughs, sows, and harvests — all verbs in same tense.',
   'difficulty':'medium'},
  {'id':'d263l_185','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'Which word is a homophone of flour?',
   'options':['Floor','Flow','Flower','Flew'],
   'correct':2,'explanation':'Flour (wheat powder) and flower (the bloom) are homophones — same sound, different spellings and meanings.',
   'difficulty':'medium'},
  {'id':'d263l_186','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Arable in farming refers to land that is:',
   'options':['Waterlogged and unfit','Suitable for ploughing and growing crops','Forest land','Grassland for grazing'],
   'correct':1,'explanation':'Arable land is land suitable for ploughing and growing crops — from Latin arare meaning to plough.',
   'difficulty':'medium'},
  {'id':'d263l_187','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'An agenda in meeting communication is:',
   'options':['Minutes of the meeting','List of items to be discussed','Report of the meeting','Invitation to the meeting'],
   'correct':1,'explanation':'An agenda is a pre-circulated list of topics to be discussed in a meeting, circulated before the meeting.',
   'difficulty':'easy'},
  {'id':'d263l_188','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Berlo SMCR model of communication stands for:',
   'options':['Source, Message, Channel, Receiver','Sender, Medium, Code, Response','Signal, Message, Channel, Reaction','Speaker, Meaning, Content, Response'],
   'correct':0,'explanation':'David Berlo SMCR model (1960): Source (sender), Message (content), Channel (medium), Receiver (audience).',
   'difficulty':'hard'},
  {'id':'d263l_189','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'The sentence type Go to the field immediately! is:',
   'options':['Interrogative','Exclamatory','Imperative','Declarative'],
   'correct':2,'explanation':'Imperative sentences give commands, instructions, or requests. The subject you is understood but not stated.',
   'difficulty':'easy'},
  {'id':'d263l_190','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'In she not only grows paddy but also vegetables, the construction used is:',
   'options':['Neither nor construction','Either or construction','Not only but also construction','Both and construction'],
   'correct':2,'explanation':'Not only...but also is a correlative conjunction pair that links two parallel elements of equal importance.',
   'difficulty':'medium'},
  {'id':'d263l_191','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'ASSERTION-REASON: Assertion (A): Empathy is important in agricultural extension communication. Reason (R): When extension workers understand farmers from their perspective, communication becomes more effective.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Empathy helps extension workers understand farmers context, building trust and making communication relevant — R correctly explains A.',
   'difficulty':'medium'},
  {'id':'d263l_192','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'Agricultural extension means:',
   'options':['Expanding farm land boundaries','Taking education and information to farmers in rural areas','Extending the sowing season','Building agricultural institutions'],
   'correct':1,'explanation':'Agricultural extension refers to transferring knowledge, skills, and technology from research institutions to farmers in rural areas.',
   'difficulty':'easy'},
  {'id':'d263l_193','subject':'english-communication','lecture':'lecture-6','lectureNo':6,
   'question':'The plural of goose is:',
   'options':['Gooses','Goose','Geese','Goosen'],
   'correct':2,'explanation':'Goose has the irregular plural geese — one of the vowel-change plurals in English.',
   'difficulty':'easy'},
  {'id':'d263l_194','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'Choose the word opposite in meaning to transparent:',
   'options':['Clear','Opaque','Visible','Bright'],
   'correct':1,'explanation':'Opaque means not transparent — it does not allow light to pass through.',
   'difficulty':'easy'},
  {'id':'d263l_195','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'The greeting Yours faithfully is used when:',
   'options':['Writing to a known person','Writing to an unknown person or organization','Writing informal letters','Writing emails to friends'],
   'correct':1,'explanation':'Yours faithfully is used when the letter begins with Dear Sir/Madam (recipient unknown). Yours sincerely is for known recipients.',
   'difficulty':'medium'},
  {'id':'d263l_196','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'An example of upward communication is:',
   'options':['Director sending orders to staff','Staff sending performance reports to supervisor','Supervisor briefing team','Director announcing policy change'],
   'correct':1,'explanation':'Upward communication flows from lower to higher levels — staff submitting reports or grievances to their supervisor.',
   'difficulty':'medium'},
  {'id':'d263l_197','subject':'english-communication','lecture':'lecture-7','lectureNo':7,
   'question':'A sentence with two independent clauses joined by and is called a:',
   'options':['Complex sentence','Simple sentence','Compound sentence','Compound-complex sentence'],
   'correct':2,'explanation':'A compound sentence has two or more independent clauses joined by a coordinating conjunction (and, but, or).',
   'difficulty':'medium'},
  {'id':'d263l_198','subject':'english-communication','lecture':'lecture-8','lectureNo':8,
   'question':'ASSERTION-REASON: Assertion (A): Written communication creates a permanent record. Reason (R): Unlike oral communication, written messages can be stored, retrieved, and referenced later.',
   'options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],
   'correct':0,'explanation':'Written communication (letters, reports, emails) leaves a permanent record. R correctly explains why — documents can be stored and referred to later.',
   'difficulty':'easy'},
  {'id':'d263l_199','subject':'english-communication','lecture':'lecture-9','lectureNo':9,
   'question':'Match writing styles: Col A: 1-Narrative, 2-Descriptive, 3-Expository, 4-Persuasive. Col B: P-presents facts, Q-tells story, R-vivid picture, S-convinces reader. Col C: i-crop disease essay, ii-farmer story, iii-field description, iv-organic farming argument',
   'options':['1-Q-ii, 2-R-iii, 3-P-i, 4-S-iv','1-P-i, 2-S-iv, 3-Q-ii, 4-R-iii','1-R-iii, 2-Q-ii, 3-S-iv, 4-P-i','1-S-iv, 2-P-i, 3-R-iii, 4-Q-ii'],
   'correct':0,'explanation':'Narrative (story=ii), Descriptive (vivid picture=field=iii), Expository (facts=crop disease=i), Persuasive (convinces=organic farming=iv).',
   'difficulty':'hard'},
  {'id':'d263l_200','subject':'english-communication','lecture':'lecture-10','lectureNo':10,
   'question':'In agricultural extension, felt need means:',
   'options':['A need identified by extension officers','A need that farmers themselves recognize and express','A need based on scientific research only','A government policy priority'],
   'correct':1,'explanation':'A felt need is a need that farmers themselves are aware of and feel — it is subjective and expressed by the beneficiaries themselves.',
   'difficulty':'medium'},
]

# ── 100 combined questions ─────────────────────────────────────────────────────
CQ = [
  {'id':'d263_101','subject':'english-communication','question':'The eight parts of speech in English include nouns, pronouns, verbs, adjectives, adverbs, prepositions, conjunctions, and:','options':['Articles','Interjections','Clauses','Phrases'],'correct':1,'explanation':'The eight parts of speech are: Noun, Pronoun, Verb, Adjective, Adverb, Preposition, Conjunction, and Interjection.','difficulty':'easy'},
  {'id':'d263_102','subject':'english-communication','question':'Which verb form is used in the Present Perfect tense?','options':['V1 base form','V2 simple past','V3 past participle','V1 + ing present participle'],'correct':2,'explanation':'Present Perfect tense uses have/has + V3 (past participle) e.g., He has grown paddy.','difficulty':'easy'},
  {'id':'d263_103','subject':'english-communication','question':'The passive voice of Farmers cultivate rice is:','options':['Rice is cultivated by farmers.','Rice was cultivated by farmers.','Rice cultivated by farmers.','Rice has been cultivated by farmers.'],'correct':0,'explanation':'Simple present active to passive: is/are + past participle. Rice is cultivated by farmers.','difficulty':'medium'},
  {'id':'d263_104','subject':'english-communication','question':'A noun derived from a verb by adding -tion is called a:','options':['Gerund','Participle','Verbal noun','Infinitive'],'correct':2,'explanation':'A verbal noun (e.g., irrigation from irrigate) is formed from a verb but functions as a noun.','difficulty':'medium'},
  {'id':'d263_105','subject':'english-communication','question':'Which sentence correctly uses the comparative degree?','options':['This mango is more sweeter than that.','This mango is sweeter than that.','This mango is most sweet.','This mango is the more sweet.'],'correct':1,'explanation':'Sweeter is the comparative form of sweet. Do not use more with one-syllable adjectives — more sweeter is a double comparative.','difficulty':'medium'},
  {'id':'d263_106','subject':'english-communication','question':'The underlined word slowly in She reads slowly is:','options':['Verb','Adjective','Noun','Adverb'],'correct':3,'explanation':'Slowly modifies the verb reads by telling how she reads — it is an adverb of manner.','difficulty':'easy'},
  {'id':'d263_107','subject':'english-communication','question':'Identify the subordinate clause in: The crops failed because there was no rain.','options':['The crops failed','because there was no rain','there was no rain','no rain'],'correct':1,'explanation':'Because there was no rain is an adverb clause of reason — it depends on the main clause The crops failed.','difficulty':'medium'},
  {'id':'d263_108','subject':'english-communication','question':'Which punctuation mark is used to introduce a list?','options':['Semicolon','Colon','Comma','Hyphen'],'correct':1,'explanation':'A colon is used to introduce a list, explanation, or example.','difficulty':'easy'},
  {'id':'d263_109','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Communication is a two-way process. Reason (R): Effective communication requires both sending a message and receiving feedback.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Communication involves encoding, transmitting, receiving, and feedback. R explains why it is two-way — feedback completes the loop.','difficulty':'easy'},
  {'id':'d263_110','subject':'english-communication','question':'Match: Col A: 1-Reading, 2-Writing, 3-Speaking, 4-Listening. Col B: P-decode written, Q-encode speech, R-decode speech, S-encode written. Col C: i-delivering a talk, ii-writing essay, iii-reading newspaper, iv-attending lecture','options':['1-P-iii, 2-S-ii, 3-Q-i, 4-R-iv','1-Q-i, 2-R-iv, 3-P-iii, 4-S-ii','1-S-ii, 2-P-iii, 3-R-iv, 4-Q-i','1-R-iv, 2-Q-i, 3-S-ii, 4-P-iii'],'correct':0,'explanation':'Reading (decode written=newspaper=iii), Writing (encode written=essay=ii), Speaking (encode speech=talk=i), Listening (decode speech=lecture=iv).','difficulty':'hard'},
  {'id':'d263_111','subject':'english-communication','question':'The correct plural of phenomenon is:','options':['Phenomenons','Phenomenas','Phenomena','Phenomenies'],'correct':2,'explanation':'Phenomenon is from Greek and forms its plural as phenomena — an irregular plural.','difficulty':'medium'},
  {'id':'d263_112','subject':'english-communication','question':'Which type of question is: You work in agriculture, do you not?','options':['Rhetorical question','Tag question','Indirect question','Wh-question'],'correct':1,'explanation':'A tag question adds a short question (do you not?) to the end of a statement to seek confirmation.','difficulty':'medium'},
  {'id':'d263_113','subject':'english-communication','question':'Identify the correct sentence:','options':['The data shows an increase.','The data show an increase.','The datas show an increase.','The datum shows increases.'],'correct':1,'explanation':'Data is the plural of datum. In formal/academic usage, data takes a plural verb: The data show.','difficulty':'hard'},
  {'id':'d263_114','subject':'english-communication','question':'Which sentence demonstrates correct use of a semicolon?','options':['Farmers grow rice; they also grow wheat.','Farmers grow rice; and wheat.','Farmers; grow rice and wheat.','Farmers grow rice; but not wheat.'],'correct':0,'explanation':'A semicolon joins two closely related independent clauses without a conjunction. Farmers grow rice; they also grow wheat is correct.','difficulty':'medium'},
  {'id':'d263_115','subject':'english-communication','question':'What is a topic sentence in a paragraph?','options':['The last sentence that concludes','The sentence that states the main idea','A sentence with a question','A supporting detail sentence'],'correct':1,'explanation':'A topic sentence states the main idea of a paragraph and usually appears at the beginning.','difficulty':'easy'},
  {'id':'d263_116','subject':'english-communication','question':'The word however in a sentence is classified as a:','options':['Coordinating conjunction','Subordinating conjunction','Conjunctive adverb','Preposition'],'correct':2,'explanation':'However is a conjunctive adverb that connects two independent clauses and shows contrast.','difficulty':'hard'},
  {'id':'d263_117','subject':'english-communication','question':'An executive summary in a report is:','options':['The longest section','A brief overview for decision makers','A list of references','The detailed methodology section'],'correct':1,'explanation':'An executive summary provides a concise overview of the report key findings and recommendations for busy decision makers.','difficulty':'medium'},
  {'id':'d263_118','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Simple sentences can still convey complex ideas. Reason (R): Complexity in writing always requires long compound-complex sentences.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':2,'explanation':'A is true — simple sentences can be powerful. R is false — clear writing values simplicity over unnecessarily complex sentences.','difficulty':'medium'},
  {'id':'d263_119','subject':'english-communication','question':'Match: Col A: 1-Abstract, 2-Introduction, 3-Conclusion, 4-References. Col B: P-credits sources, Q-brief summary, R-closes discussion, S-sets context. Col C: i-list of books used, ii-this paper examines, iii-in summary, iv-this study investigates','options':['1-Q-iv, 2-S-ii, 3-R-iii, 4-P-i','1-P-i, 2-Q-iv, 3-S-ii, 4-R-iii','1-S-ii, 2-R-iii, 3-P-i, 4-Q-iv','1-R-iii, 2-P-i, 3-Q-iv, 4-S-ii'],'correct':0,'explanation':'Abstract (brief summary=investigates=iv), Introduction (sets context=examines=ii), Conclusion (closes=in summary=iii), References (credits=books list=i).','difficulty':'hard'},
  {'id':'d263_120','subject':'english-communication','question':'The word can in You can improve your communication skills expresses:','options':['Obligation','Ability or possibility','Probability','Formal permission'],'correct':1,'explanation':'Can is a modal verb expressing ability or possibility here — You are able to or it is possible to improve.','difficulty':'easy'},
  {'id':'d263_121','subject':'english-communication','question':'Choose the correct form: The research has _____ significant results.','options':['yield','yielded','yielding','yields'],'correct':1,'explanation':'After has (present perfect auxiliary), the past participle (V3) is used: has yielded.','difficulty':'medium'},
  {'id':'d263_122','subject':'english-communication','question':'The greeting Yours faithfully is used when:','options':['Writing to a known person','Writing to an unknown person or organization','Writing informal letters','Writing emails to friends'],'correct':1,'explanation':'Yours faithfully is used when the letter begins with Dear Sir/Madam (recipient unknown). Yours sincerely is for known recipients.','difficulty':'medium'},
  {'id':'d263_123','subject':'english-communication','question':'The term coherence in writing means:','options':['Long sentence structure','Logical connection and flow between ideas','Use of technical words','Repetition of key terms'],'correct':1,'explanation':'Coherence is the quality of being logically connected — ideas flow smoothly from one to another, making text easy to understand.','difficulty':'medium'},
  {'id':'d263_124','subject':'english-communication','question':'Which sentence is grammatically correct?','options':['Between you and I, the crop is good.','Between you and me, the crop is good.','Between you and mine, the crop is good.','Between you and myself, the crop is good.'],'correct':1,'explanation':'After prepositions (between, with, for, by), use objective pronouns (me, him, her, us). Between you and me is correct.','difficulty':'medium'},
  {'id':'d263_125','subject':'english-communication','question':'In agricultural extension, which communication method reaches the largest audience at one time?','options':['Farm visits','Group meetings','Mass media such as radio and TV','Demonstration'],'correct':2,'explanation':'Mass media (radio, TV, newspapers) can reach millions of farmers simultaneously, making them the most wide-reaching method.','difficulty':'easy'},
  {'id':'d263_126','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Extension workers should use simple language when communicating with farmers. Reason (R): Farmers may have low literacy levels and using technical jargon creates communication barriers.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'R correctly explains why simple language is necessary — jargon and complex words create barriers for farmers with limited education.','difficulty':'easy'},
  {'id':'d263_127','subject':'english-communication','question':'Match: Col A: 1-Skimming, 2-Scanning, 3-Intensive reading, 4-Extensive reading. Col B: P-find specific info, Q-careful detailed reading, R-get general idea, S-reading for pleasure. Col C: i-reading a novel, ii-looking for date, iii-studying textbook, iv-reading headlines','options':['1-R-iv, 2-P-ii, 3-Q-iii, 4-S-i','1-P-ii, 2-R-iv, 3-S-i, 4-Q-iii','1-Q-iii, 2-S-i, 3-P-ii, 4-R-iv','1-S-i, 2-Q-iii, 3-R-iv, 4-P-ii'],'correct':0,'explanation':'Skimming (general idea=headlines=iv), Scanning (find specific=date=ii), Intensive (detailed study=textbook=iii), Extensive (pleasure=novel=i).','difficulty':'hard'},
  {'id':'d263_128','subject':'english-communication','question':'Which word is a homophone of flour?','options':['Floor','Flow','Flower','Flew'],'correct':2,'explanation':'Flour (wheat powder) and flower (the bloom) are homophones — they sound identical but have different spellings and meanings.','difficulty':'medium'},
  {'id':'d263_129','subject':'english-communication','question':'What does SWOT stand for in communication and management?','options':['Skills, Work, Output, Training','Strengths, Weaknesses, Opportunities, Threats','Study, Writing, Operations, Trends','Systems, Work, Organization, Tasks'],'correct':1,'explanation':'SWOT analysis stands for Strengths, Weaknesses, Opportunities, and Threats — used in planning and management communication.','difficulty':'easy'},
  {'id':'d263_130','subject':'english-communication','question':'Provided that it rains, we will have a good harvest — the underlined clause is:','options':['Noun clause','Adjective clause','Adverb clause of condition','Independent clause'],'correct':2,'explanation':'Provided that it rains is an adverb clause of condition — it sets the condition for the main clause.','difficulty':'medium'},
  {'id':'d263_131','subject':'english-communication','question':'Which is an example of euphemism?','options':['The crop died.','The plant passed away.','He destroyed the field.','The machine broke.'],'correct':1,'explanation':'A euphemism substitutes a mild expression for an unpleasant one. Passed away for died is a classic euphemism.','difficulty':'medium'},
  {'id':'d263_132','subject':'english-communication','question':'The sentence type Go to the field immediately! is:','options':['Interrogative','Exclamatory','Imperative','Declarative'],'correct':2,'explanation':'Imperative sentences give commands, instructions, or requests. The subject you is understood but not stated.','difficulty':'easy'},
  {'id':'d263_133','subject':'english-communication','question':'Match prefixes: Col A: 1-against, 2-before, 3-too much, 4-again. Col B: P-over, Q-re, R-anti, S-pre. Col C: i-overwater, ii-resow, iii-antifungal, iv-pre-harvest','options':['1-R-iii, 2-S-iv, 3-P-i, 4-Q-ii','1-S-iv, 2-Q-ii, 3-R-iii, 4-P-i','1-P-i, 2-R-iii, 3-Q-ii, 4-S-iv','1-Q-ii, 2-P-i, 3-S-iv, 4-R-iii'],'correct':0,'explanation':'Anti- (against=antifungal=iii), Pre- (before=pre-harvest=iv), Over- (too much=overwater=i), Re- (again=resow=ii).','difficulty':'hard'},
  {'id':'d263_134','subject':'english-communication','question':'The term rhetoric in communication refers to:','options':['Empty talk','The art of effective or persuasive speaking and writing','Technical report writing','Formal grammar rules'],'correct':1,'explanation':'Rhetoric is the art of effective communication — using language skillfully to persuade, inform, or motivate an audience.','difficulty':'medium'},
  {'id':'d263_135','subject':'english-communication','question':'In the Shannon-Weaver model of communication, which are the five components?','options':['Speaker, Message, Noise, Receiver, Effect','Source, Transmitter, Channel, Receiver, Destination','Encoder, Message, Channel, Decoder, Feedback','Sender, Encoding, Medium, Decoding, Feedback'],'correct':1,'explanation':'Shannon-Weaver (1949) model: Information source, Transmitter, Channel (with noise), Receiver, Destination.','difficulty':'hard'},
  {'id':'d263_136','subject':'english-communication','question':'The conjunction since can express:','options':['Contrast and reason','Time and reason','Condition and purpose','Concession and result'],'correct':1,'explanation':'Since can express time (Since 1990, agriculture changed) or reason (Since it rained, crops grew). It serves dual functions.','difficulty':'medium'},
  {'id':'d263_137','subject':'english-communication','question':'In: She is as tall as a sunflower plant, the figure of speech used is:','options':['Metaphor','Simile','Alliteration','Hyperbole'],'correct':1,'explanation':'Simile compares two things using as...as or like. As tall as a sunflower plant is a simile.','difficulty':'easy'},
  {'id':'d263_138','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Active voice is generally preferred over passive voice in writing. Reason (R): Active voice sentences are clearer, more direct, and show who is performing the action.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Active voice (The farmer waters plants) is clearer than passive (Plants are watered). R correctly explains why active voice is preferred.','difficulty':'medium'},
  {'id':'d263_139','subject':'english-communication','question':'The word arable in agriculture refers to land that is:','options':['Waterlogged and unfit','Suitable for ploughing and growing crops','Forest land','Grassland for grazing'],'correct':1,'explanation':'Arable land is land suitable for ploughing and growing crops — from Latin arare meaning to plough.','difficulty':'medium'},
  {'id':'d263_140','subject':'english-communication','question':'Match: Col A: 1-Noun to adjective, 2-Verb to noun, 3-Adjective to adverb, 4-Noun to verb. Col B: P-tion/sion, Q-ly, R-al/ful/ous, S-ify/ize. Col C: i-fertilize, ii-agricultural, iii-quickly, iv-irrigation','options':['1-R-ii, 2-P-iv, 3-Q-iii, 4-S-i','1-P-iv, 2-R-ii, 3-S-i, 4-Q-iii','1-Q-iii, 2-S-i, 3-R-ii, 4-P-iv','1-S-i, 2-Q-iii, 3-P-iv, 4-R-ii'],'correct':0,'explanation':'Noun-Adj (-al/ful/ous: agricultural=ii), Verb-Noun (-tion: irrigation=iv), Adj-Adv (-ly: quickly=iii), Noun-Verb (-ize: fertilize=i).','difficulty':'hard'},
  {'id':'d263_141','subject':'english-communication','question':'The indirect speech of He said, I will come tomorrow is:','options':['He said that he will come tomorrow.','He said that he would come the next day.','He said that he came the next day.','He said that I would come tomorrow.'],'correct':1,'explanation':'In indirect speech: will becomes would, tomorrow becomes the next day, and pronoun I changes to he.','difficulty':'medium'},
  {'id':'d263_142','subject':'english-communication','question':'The correct use of principal vs principle: The _____ agreed to the proposal (head of institution).','options':['Principle — as head of institution','Principal — as head of institution','Either can be used','Neither is appropriate'],'correct':1,'explanation':'Principal (person) = head of institution/school. Principle (thing) = a fundamental rule. Here the person (principal) is correct.','difficulty':'medium'},
  {'id':'d263_143','subject':'english-communication','question':'Which modal verb expresses obligation in: _____ farmers adopt drip irrigation to save water.','options':['Can','May','Should','Will'],'correct':2,'explanation':'Should expresses obligation or strong recommendation. Farmers should adopt drip irrigation — it is advisable.','difficulty':'easy'},
  {'id':'d263_144','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Pronunciation and stress patterns affect the meaning of spoken English. Reason (R): Changing word stress can change a word\'s part of speech (e.g., REcord vs reCORD).','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Stress does affect meaning and function. REcord (noun) vs reCORD (verb) — R correctly demonstrates and explains A.','difficulty':'medium'},
  {'id':'d263_145','subject':'english-communication','question':'A circular in official communication is issued to:','options':['One specific individual','A group of people simultaneously','External organizations only','Government bodies only'],'correct':1,'explanation':'A circular is an official communication sent to a group of people (department staff, members) simultaneously.','difficulty':'easy'},
  {'id':'d263_146','subject':'english-communication','question':'Choose the word that correctly fills: The extension officer gave a _____ presentation on drip irrigation.','options':['verbose','concise','ambiguous','redundant'],'correct':1,'explanation':'Concise means brief and clear — ideal for effective presentations. It is the most appropriate choice here.','difficulty':'medium'},
  {'id':'d263_147','subject':'english-communication','question':'Verbal communication specifically refers to:','options':['Speaking only','Writing only','Use of words both spoken and written','Body language and gestures'],'correct':2,'explanation':'Verbal communication encompasses all communication using words — both spoken (oral) and written forms.','difficulty':'medium'},
  {'id':'d263_148','subject':'english-communication','question':'Which word has a negative connotation?','options':['Thrifty','Economical','Miserly','Frugal'],'correct':2,'explanation':'Miserly carries a negative connotation — it implies excessive unwillingness to spend. Thrifty, economical, and frugal are more positive.','difficulty':'medium'},
  {'id':'d263_149','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Written communication creates a permanent record. Reason (R): Unlike oral communication, written messages can be stored, retrieved, and referenced later.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Written communication (letters, reports, emails) leaves a permanent record. R correctly explains why — documents can be stored and referred to later.','difficulty':'easy'},
  {'id':'d263_150','subject':'english-communication','question':'Match: Col A: 1-Simple, 2-Compound, 3-Complex, 4-Compound-complex. Col B: P-two independent + one dependent, Q-one independent, R-one independent + one dependent, S-two independent. Col C: i-She farms, ii-She farms and he sells, iii-She farms because it rains, iv-She farms and he sells when prices rise','options':['1-Q-i, 2-S-ii, 3-R-iii, 4-P-iv','1-S-ii, 2-R-iii, 3-P-iv, 4-Q-i','1-R-iii, 2-P-iv, 3-Q-i, 4-S-ii','1-P-iv, 2-Q-i, 3-S-ii, 4-R-iii'],'correct':0,'explanation':'Simple (one independent=i), Compound (two independent=ii), Complex (independent+dependent=iii), Compound-complex (two+one dependent=iv).','difficulty':'hard'},
  {'id':'d263_151','subject':'english-communication','question':'Denotation of a word best describes:','options':['Emotional associations of a word','Literal dictionary meaning of a word','Figurative meaning in context','Sound patterns of a word'],'correct':1,'explanation':'Denotation is the direct, literal meaning of a word as found in the dictionary, without emotional associations.','difficulty':'medium'},
  {'id':'d263_152','subject':'english-communication','question':'The process of converting received spoken message back to meaning is called:','options':['Encoding','Transmission','Decoding','Feedback'],'correct':2,'explanation':'Decoding is the receiver process of interpreting and understanding the transmitted message.','difficulty':'easy'},
  {'id':'d263_153','subject':'english-communication','question':'Choose the correct form of verb: The committee _____ its decision yesterday.','options':['announce','has announced','announced','will announce'],'correct':2,'explanation':'Yesterday signals simple past tense. Announced (simple past) is correct.','difficulty':'easy'},
  {'id':'d263_154','subject':'english-communication','question':'In agricultural extension, feedback from farmers helps extension workers to:','options':['Increase their salary','Evaluate effectiveness and improve methods','Expand farmland','Write more reports'],'correct':1,'explanation':'Feedback tells extension workers whether their messages were received, understood, and applied — enabling them to improve their approach.','difficulty':'medium'},
  {'id':'d263_155','subject':'english-communication','question':'Match: Col A: 1-Communication barriers. 1-Language, 2-Physical, 3-Cultural, 4-Emotional. Col B: P-psychological, Q-environmental, R-sociocultural, S-linguistic. Col C: i-use local language, ii-reduce noise, iii-build emotional safety, iv-cultural sensitivity training','options':['1-S-i, 2-Q-ii, 3-R-iv, 4-P-iii','1-Q-ii, 2-R-iv, 3-P-iii, 4-S-i','1-R-iv, 2-P-iii, 3-S-i, 4-Q-ii','1-P-iii, 2-S-i, 3-Q-ii, 4-R-iv'],'correct':0,'explanation':'Language (linguistic=use local language=i), Physical (environmental=reduce noise=ii), Cultural (sociocultural=sensitivity training=iv), Emotional (psychological=safety=iii).','difficulty':'hard'},
  {'id':'d263_156','subject':'english-communication','question':'Which is correct: She _____ the field before the rains arrived.','options':['ploughs','ploughed','has ploughed','will plough'],'correct':1,'explanation':'Before the rains arrived sets context in the past. Simple past ploughed is correct for a completed action.','difficulty':'easy'},
  {'id':'d263_157','subject':'english-communication','question':'The rhetorical question Is there anything more important than food security? is used to:','options':['Seek information','Emphasize a point without expecting an answer','Express doubt','Request clarification'],'correct':1,'explanation':'A rhetorical question is asked for effect to emphasize a point — no actual answer is expected.','difficulty':'medium'},
  {'id':'d263_158','subject':'english-communication','question':'Which of the following is a concrete noun?','options':['Freedom','Knowledge','Irrigation canal','Patience'],'correct':2,'explanation':'A concrete noun names something physical that can be seen or touched. Irrigation canal is tangible — it is a concrete noun.','difficulty':'easy'},
  {'id':'d263_159','subject':'english-communication','question':'The idiom to plough a lonely furrow means:','options':['Doing agricultural work alone','Working independently without support from others','Ploughing inefficiently','Starting a new farm alone'],'correct':1,'explanation':'Ploughing a lonely furrow is an idiom meaning to work alone on something without help or support from others.','difficulty':'hard'},
  {'id':'d263_160','subject':'english-communication','question':'The term grapevine communication refers to:','options':['Agricultural news channels','Official written memos','Informal rumour network in organizations','Electronic mass media'],'correct':2,'explanation':'Grapevine communication is an informal channel through which rumours spread quickly in organizations.','difficulty':'easy'},
  {'id':'d263_161','subject':'english-communication','question':'The word agriculture is to farming as horticulture is to:','options':['Forest cultivation','Garden cultivation','Soil science','Livestock rearing'],'correct':1,'explanation':'Horticulture (from Latin hortus=garden and colere=to cultivate) refers specifically to garden cultivation including fruits, vegetables, and flowers.','difficulty':'medium'},
  {'id':'d263_162','subject':'english-communication','question':'In group communication, the person who guides the discussion and ensures everyone participates is the:','options':['Secretary','Treasurer','Facilitator or Moderator','Observer'],'correct':2,'explanation':'A facilitator or moderator guides group discussions, manages time, ensures balanced participation, and keeps discussion on track.','difficulty':'easy'},
  {'id':'d263_163','subject':'english-communication','question':'The word nevertheless in writing functions as a:','options':['Coordinating conjunction','Preposition','Conjunctive adverb showing contrast','Subordinating conjunction'],'correct':2,'explanation':'Nevertheless is a conjunctive adverb showing contrast/concession. It connects two independent clauses.','difficulty':'hard'},
  {'id':'d263_164','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Listening is a passive activity. Reason (R): Good listening requires conscious effort, attention, and mental engagement with what is being said.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':3,'explanation':'A is false — listening is an active process. R is true — effective listening requires active mental engagement, contradicting A.','difficulty':'medium'},
  {'id':'d263_165','subject':'english-communication','question':'The correct use of between vs among: Use _____ for exactly two items, _____ for three or more.','options':['among, between','between, among','between, between','among, among'],'correct':1,'explanation':'Between is typically used for exactly two items or distinct things; among is used for three or more in a group.','difficulty':'medium'},
  {'id':'d263_166','subject':'english-communication','question':'Match: Col A: 1-Informative, 2-Persuasive, 3-Entertaining, 4-Ceremonial speeches. Col B: P-influence beliefs, Q-mark an occasion, R-amuse, S-convey knowledge. Col C: i-humorous speech, ii-welcome address, iii-lecture on soil, iv-campaign speech','options':['1-S-iii, 2-P-iv, 3-R-i, 4-Q-ii','1-P-iv, 2-S-iii, 3-Q-ii, 4-R-i','1-R-i, 2-Q-ii, 3-P-iv, 4-S-iii','1-Q-ii, 2-R-i, 3-S-iii, 4-P-iv'],'correct':0,'explanation':'Informative (knowledge=lecture=iii), Persuasive (influence=campaign speech=iv), Entertaining (amuse=humorous=i), Ceremonial (occasion=welcome=ii).','difficulty':'hard'},
  {'id':'d263_167','subject':'english-communication','question':'What is an agenda in meeting communication?','options':['Minutes of the meeting','List of items to be discussed','Report of the meeting','Invitation to the meeting'],'correct':1,'explanation':'An agenda is a pre-circulated list of topics to be discussed in a meeting.','difficulty':'easy'},
  {'id':'d263_168','subject':'english-communication','question':'In communication, proxemics is the study of:','options':['Body movement and posture','Voice tone and pitch','Use of personal space and physical distance','Eye contact patterns'],'correct':2,'explanation':'Proxemics (coined by Edward T. Hall) is the study of how people use and perceive physical space in communication.','difficulty':'hard'},
  {'id':'d263_169','subject':'english-communication','question':'Agriculture is the backbone of India — the word backbone is used as:','options':['Simile','Metaphor','Personification','Alliteration'],'correct':1,'explanation':'Calling agriculture the backbone is a metaphor — a direct comparison without like or as, implying it is the chief support.','difficulty':'medium'},
  {'id':'d263_170','subject':'english-communication','question':'In Neither the farmer nor the labourers were present, the verb agrees with:','options':['farmer (singular)','labourers (plural)','Neither (singular)','The first subject'],'correct':1,'explanation':'With neither...nor, the verb agrees with the subject closer to it. Labourers (plural) is closer, so were (plural) is correct.','difficulty':'hard'},
  {'id':'d263_171','subject':'english-communication','question':'A paragraph must have unity — this means:','options':['Only two sentences per paragraph','Every sentence should relate to and support the topic sentence','Only the topic sentence matters','Paragraphs must all be the same length'],'correct':1,'explanation':'Unity means all sentences focus on one idea. Every sentence must relate to the topic sentence for unity.','difficulty':'easy'},
  {'id':'d263_172','subject':'english-communication','question':'The term plagiarism in academic writing means:','options':['Writing in simple language','Copying someone else\'s work without acknowledgment','Citing too many references','Using passive voice'],'correct':1,'explanation':'Plagiarism is presenting someone else\'s words, ideas, or work as your own without proper citation — it is academic dishonesty.','difficulty':'easy'},
  {'id':'d263_173','subject':'english-communication','question':'The word harvest can function as which parts of speech?','options':['Adjective only','Adverb only','Noun and verb','Noun only'],'correct':2,'explanation':'Harvest can be a noun (The harvest was good) or a verb (Farmers harvest crops in October) — it has dual functions.','difficulty':'medium'},
  {'id':'d263_174','subject':'english-communication','question':'Choose the word that correctly fills: Despite the drought, the farmer remained _____ about the next season.','options':['pessimistic','hopeless','optimistic','indifferent'],'correct':2,'explanation':'Optimistic means hopeful about the future — it fits logically as a positive attitude despite adversity.','difficulty':'easy'},
  {'id':'d263_175','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Oral communication is the most ancient form of communication. Reason (R): Writing was developed by humans long before spoken language.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':2,'explanation':'A is true — oral communication is the oldest form. R is false — spoken language came first; writing was developed much later.','difficulty':'medium'},
  {'id':'d263_176','subject':'english-communication','question':'The phrase agricultural extension in education means:','options':['Expanding farm land boundaries','Taking education and information to farmers in rural areas','Extending the sowing season','Building agricultural institutions'],'correct':1,'explanation':'Agricultural extension refers to transferring knowledge, skills, and technology from research institutions to farmers in rural areas.','difficulty':'easy'},
  {'id':'d263_177','subject':'english-communication','question':'In agricultural extension, felt need means:','options':['A need identified by extension officers','A need that farmers themselves recognize and express','A need based on scientific research only','A government policy priority'],'correct':1,'explanation':'A felt need is a need that farmers themselves are aware of and feel — it is subjective and expressed by the beneficiaries.','difficulty':'medium'},
  {'id':'d263_178','subject':'english-communication','question':'Which is correct word order for English adjectives (opinion-size-age-shape-material)?','options':['Two large brown old wooden tables','Two old large brown wooden tables','Two small old round metal boxes','Large two brown old wooden tables'],'correct':2,'explanation':'English adjective order: Opinion-Size-Age-Shape-Color-Origin-Material-Purpose. Small (size) old (age) round (shape) metal (material) boxes is correct.','difficulty':'hard'},
  {'id':'d263_179','subject':'english-communication','question':'Expository writing is writing that:','options':['Tells a story','Describes a scene vividly','Explains and informs using facts','Persuades the reader to take action'],'correct':2,'explanation':'Expository writing explains a topic objectively using facts, statistics, and examples — without the author\'s personal opinion.','difficulty':'easy'},
  {'id':'d263_180','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Good oral communication requires both speaking and listening skills. Reason (R): Communication is complete only when the receiver understands the message — making listening equally important as speaking.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Effective oral communication is a dialogue — R correctly explains that understanding (through listening) is essential to complete the process.','difficulty':'easy'},
  {'id':'d263_181','subject':'english-communication','question':'The study of intonation and stress patterns affecting meaning in spoken language is called:','options':['Morphology','Syntax','Prosody','Pragmatics'],'correct':2,'explanation':'Prosody is the study of rhythm, stress, and intonation in speech — these patterns significantly affect the meaning of spoken utterances.','difficulty':'hard'},
  {'id':'d263_182','subject':'english-communication','question':'The plural of goose is:','options':['Gooses','Goose','Geese','Goosen'],'correct':2,'explanation':'Goose has the irregular plural geese — one of the vowel-change plurals in English.','difficulty':'easy'},
  {'id':'d263_183','subject':'english-communication','question':'Which word is both a noun and a verb in English?','options':['Beautiful','Slowly','Harvest','And'],'correct':2,'explanation':'Harvest can be a noun (The harvest was good) or a verb (Farmers harvest crops in October) — it has dual function.','difficulty':'medium'},
  {'id':'d263_184','subject':'english-communication','question':'The sentence Unless you irrigate, the crop will die is:','options':['A statement of fact','A conditional sentence','An exclamation','A passive voice sentence'],'correct':1,'explanation':'Unless introduces a conditional clause. Unless you irrigate (if you do NOT irrigate) the crop will die — it is a conditional sentence.','difficulty':'medium'},
  {'id':'d263_185','subject':'english-communication','question':'Empathy in communication means:','options':['Feeling superior to others','Understanding and sharing others\' feelings and perspectives','Expressing one\'s own feelings loudly','Avoiding emotional topics'],'correct':1,'explanation':'Empathy is the ability to understand and share the feelings of another — essential for effective and supportive communication.','difficulty':'easy'},
  {'id':'d263_186','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Body language accounts for a major portion of communication impact. Reason (R): Non-verbal cues (posture, gestures, expressions) carry greater weight than words alone.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Studies show about 55% of communication is body language. R correctly explains why non-verbal communication has high impact.','difficulty':'medium'},
  {'id':'d263_187','subject':'english-communication','question':'A split infinitive places what between to and the verb?','options':['A noun','An adverb','An adjective','A pronoun'],'correct':1,'explanation':'A split infinitive places an adverb between to and the verb. Example: to quickly grow — quickly splits the infinitive.','difficulty':'hard'},
  {'id':'d263_188','subject':'english-communication','question':'Which sentence uses its vs its correctly (belonging to the crop)?','options':['The crop has lost it\'s color.','The crop has lost its color.','It\'s color has faded.','The crop lost it\'s leaves.'],'correct':1,'explanation':'Its (no apostrophe) is a possessive pronoun. It\'s = it is. The crop has lost its color (belonging to the crop) is correct.','difficulty':'medium'},
  {'id':'d263_189','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Idioms should be used sparingly in technical agricultural writing. Reason (R): Technical writing aims for precision and clarity; idioms can be ambiguous, especially for non-native speakers.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Technical writing requires precise, unambiguous language. R correctly explains why idioms (which carry figurative meaning) should be avoided.','difficulty':'medium'},
  {'id':'d263_190','subject':'english-communication','question':'The word versatile as used in Rice is a versatile crop means:','options':['Difficult to grow','Adapted to a wide range of uses','Expensive to market','Sensitive to climate'],'correct':1,'explanation':'Versatile means able to adapt to many functions or conditions. Rice is versatile because it is used in many food products.','difficulty':'easy'},
  {'id':'d263_191','subject':'english-communication','question':'The correct question tag for Let us go to the demonstration plot is:','options':['won\'t we','don\'t we','shall we','will we'],'correct':2,'explanation':'For sentences starting with Let us, the question tag is shall we? Example: Let us go, shall we?','difficulty':'hard'},
  {'id':'d263_192','subject':'english-communication','question':'Which sentence demonstrates correct parallel structure?','options':['She likes farming, to garden, and weeding.','She likes to farm, to garden, and to weed.','She likes farming, gardening, and to weed.','She likes to farm, gardening, and weed.'],'correct':1,'explanation':'Parallelism requires consistent grammatical form. She likes to farm, to garden, and to weed (all infinitives) is correctly parallel.','difficulty':'medium'},
  {'id':'d263_193','subject':'english-communication','question':'The term agronomy refers to:','options':['Study of farm animals','Science of soil management and crop production','Study of plant diseases','Forest science'],'correct':1,'explanation':'Agronomy is the science and technology of producing and using plants for food, fuel, and land management — focusing on soil management and crop production.','difficulty':'medium'},
  {'id':'d263_194','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): A curriculum vitae (CV) is longer and more detailed than a resume. Reason (R): A CV includes complete academic and professional history, while a resume is a brief summary.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Both statements are true. R correctly explains why a CV is longer — it provides complete academic and career details.','difficulty':'medium'},
  {'id':'d263_195','subject':'english-communication','question':'Which sentence has a misplaced modifier?','options':['The farmer used a sharp sickle.','I saw a bird watching from the window.','She planted seeds carefully.','He harvested the golden wheat.'],'correct':1,'explanation':'Watching from the window appears to modify bird — a misplaced modifier. It should be: Watching from the window, I saw a bird.','difficulty':'hard'},
  {'id':'d263_196','subject':'english-communication','question':'What is précis writing?','options':['Expanding a passage into a longer version','Summarizing a passage in one-third its length','Translating a passage into another language','Copying a passage verbatim'],'correct':1,'explanation':'Precis writing is the art of summarizing a passage into about one-third of its original length while retaining all key ideas.','difficulty':'medium'},
  {'id':'d263_197','subject':'english-communication','question':'Which is an example of upward communication?','options':['Director sending orders to staff','Staff sending performance reports to supervisor','Supervisor briefing team','Director announcing policy change'],'correct':1,'explanation':'Upward communication flows from lower to higher levels — staff submitting reports or grievances to their supervisor.','difficulty':'medium'},
  {'id':'d263_198','subject':'english-communication','question':'The figure of speech in Agriculture is the backbone of India is:','options':['Simile','Metaphor','Personification','Alliteration'],'correct':1,'explanation':'Calling agriculture the backbone is a metaphor — a direct comparison without like or as, implying it is the chief support.','difficulty':'medium'},
  {'id':'d263_199','subject':'english-communication','question':'ASSERTION-REASON: Assertion (A): Extension workers should empathize with farmers. Reason (R): Empathy helps extension workers understand farmers\' problems from their perspective, building trust and making communication more effective.','options':['Both A and R are true and R is the correct explanation of A','Both A and R are true but R is NOT the correct explanation of A','A is true but R is false','A is false but R is true'],'correct':0,'explanation':'Empathy helps extension workers understand farmers context, building trust and making communication relevant — R correctly explains A.','difficulty':'medium'},
  {'id':'d263_200','subject':'english-communication','question':'Match speech types: Col A: 1-Persuasive, 2-Informative, 3-Entertaining, 4-Ceremonial. Col B: P-conveys knowledge, Q-marks occasion, R-convinces audience, S-amuses. Col C: i-campaign speech, ii-welcome address, iii-lecture on crops, iv-comedy show','options':['1-R-i, 2-P-iii, 3-S-iv, 4-Q-ii','1-P-iii, 2-R-i, 3-Q-ii, 4-S-iv','1-Q-ii, 2-S-iv, 3-R-i, 4-P-iii','1-S-iv, 2-Q-ii, 3-P-iii, 4-R-i'],'correct':0,'explanation':'Persuasive (convinces=campaign speech=i), Informative (knowledge=lecture=iii), Entertaining (amuses=comedy=iv), Ceremonial (occasion=welcome=ii).','difficulty':'hard'},
]

LQ = shuffle_q(LQ)
CQ = shuffle_q(CQ)

import os
append_to_file(os.path.join(BASE, 'da-263-lectures.ts'), LQ, True)
append_to_file(os.path.join(BASE, 'da-263.ts'), CQ, False)
print("DA-263 done!")
